// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /api/v1/auth/login-options`.
    /// - Remark: Generated from `#/paths//api/v1/auth/login-options/get(AuthController_loginOptions)`.
    func authControllerLoginOptions(_ input: Operations.AuthControllerLoginOptions.Input) async throws -> Operations.AuthControllerLoginOptions.Output
    /// - Remark: HTTP `POST /api/v1/auth/login`.
    /// - Remark: Generated from `#/paths//api/v1/auth/login/post(AuthController_login)`.
    func authControllerLogin(_ input: Operations.AuthControllerLogin.Input) async throws -> Operations.AuthControllerLogin.Output
    /// - Remark: HTTP `POST /api/v1/auth/refresh`.
    /// - Remark: Generated from `#/paths//api/v1/auth/refresh/post(AuthController_refresh)`.
    func authControllerRefresh(_ input: Operations.AuthControllerRefresh.Input) async throws -> Operations.AuthControllerRefresh.Output
    /// - Remark: HTTP `POST /api/v1/auth/logout`.
    /// - Remark: Generated from `#/paths//api/v1/auth/logout/post(AuthController_logout)`.
    func authControllerLogout(_ input: Operations.AuthControllerLogout.Input) async throws -> Operations.AuthControllerLogout.Output
    /// - Remark: HTTP `GET /api/v1/auth/me`.
    /// - Remark: Generated from `#/paths//api/v1/auth/me/get(AuthController_me)`.
    func authControllerMe(_ input: Operations.AuthControllerMe.Input) async throws -> Operations.AuthControllerMe.Output
    /// - Remark: HTTP `POST /api/v1/books/query`.
    /// - Remark: Generated from `#/paths//api/v1/books/query/post(BookController_globalQuery)`.
    func bookControllerGlobalQuery(_ input: Operations.BookControllerGlobalQuery.Input) async throws -> Operations.BookControllerGlobalQuery.Output
    /// - Remark: HTTP `GET /api/v1/books/files/{fileId}/progress`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/get(BookController_getFileProgress)`.
    func bookControllerGetFileProgress(_ input: Operations.BookControllerGetFileProgress.Input) async throws -> Operations.BookControllerGetFileProgress.Output
    /// - Remark: HTTP `POST /api/v1/books/files/{fileId}/progress`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/post(BookController_saveFileProgress)`.
    func bookControllerSaveFileProgress(_ input: Operations.BookControllerSaveFileProgress.Input) async throws -> Operations.BookControllerSaveFileProgress.Output
    /// - Remark: HTTP `POST /api/v1/books/files/{fileId}/sessions`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/sessions/post(ReadingSessionController_saveSession)`.
    func readingSessionControllerSaveSession(_ input: Operations.ReadingSessionControllerSaveSession.Input) async throws -> Operations.ReadingSessionControllerSaveSession.Output
    /// - Remark: HTTP `GET /api/v1/books/{bookId}/bookmarks`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/get(BookmarkController_getBookmarks)`.
    func bookmarkControllerGetBookmarks(_ input: Operations.BookmarkControllerGetBookmarks.Input) async throws -> Operations.BookmarkControllerGetBookmarks.Output
    /// - Remark: HTTP `POST /api/v1/books/{bookId}/bookmarks`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/post(BookmarkController_createBookmark)`.
    func bookmarkControllerCreateBookmark(_ input: Operations.BookmarkControllerCreateBookmark.Input) async throws -> Operations.BookmarkControllerCreateBookmark.Output
    /// - Remark: HTTP `DELETE /api/v1/books/{bookId}/bookmarks/{bookmarkId}`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/{bookmarkId}/delete(BookmarkController_deleteBookmark)`.
    func bookmarkControllerDeleteBookmark(_ input: Operations.BookmarkControllerDeleteBookmark.Input) async throws -> Operations.BookmarkControllerDeleteBookmark.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /api/v1/auth/login-options`.
    /// - Remark: Generated from `#/paths//api/v1/auth/login-options/get(AuthController_loginOptions)`.
    public func authControllerLoginOptions(headers: Operations.AuthControllerLoginOptions.Input.Headers = .init()) async throws -> Operations.AuthControllerLoginOptions.Output {
        try await authControllerLoginOptions(Operations.AuthControllerLoginOptions.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /api/v1/auth/login`.
    /// - Remark: Generated from `#/paths//api/v1/auth/login/post(AuthController_login)`.
    public func authControllerLogin(
        headers: Operations.AuthControllerLogin.Input.Headers = .init(),
        body: Operations.AuthControllerLogin.Input.Body
    ) async throws -> Operations.AuthControllerLogin.Output {
        try await authControllerLogin(Operations.AuthControllerLogin.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/auth/refresh`.
    /// - Remark: Generated from `#/paths//api/v1/auth/refresh/post(AuthController_refresh)`.
    public func authControllerRefresh(
        headers: Operations.AuthControllerRefresh.Input.Headers = .init(),
        body: Operations.AuthControllerRefresh.Input.Body
    ) async throws -> Operations.AuthControllerRefresh.Output {
        try await authControllerRefresh(Operations.AuthControllerRefresh.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/auth/logout`.
    /// - Remark: Generated from `#/paths//api/v1/auth/logout/post(AuthController_logout)`.
    public func authControllerLogout(
        headers: Operations.AuthControllerLogout.Input.Headers = .init(),
        body: Operations.AuthControllerLogout.Input.Body
    ) async throws -> Operations.AuthControllerLogout.Output {
        try await authControllerLogout(Operations.AuthControllerLogout.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/auth/me`.
    /// - Remark: Generated from `#/paths//api/v1/auth/me/get(AuthController_me)`.
    public func authControllerMe(headers: Operations.AuthControllerMe.Input.Headers = .init()) async throws -> Operations.AuthControllerMe.Output {
        try await authControllerMe(Operations.AuthControllerMe.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /api/v1/books/query`.
    /// - Remark: Generated from `#/paths//api/v1/books/query/post(BookController_globalQuery)`.
    public func bookControllerGlobalQuery(
        headers: Operations.BookControllerGlobalQuery.Input.Headers = .init(),
        body: Operations.BookControllerGlobalQuery.Input.Body
    ) async throws -> Operations.BookControllerGlobalQuery.Output {
        try await bookControllerGlobalQuery(Operations.BookControllerGlobalQuery.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/books/files/{fileId}/progress`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/get(BookController_getFileProgress)`.
    public func bookControllerGetFileProgress(
        path: Operations.BookControllerGetFileProgress.Input.Path,
        headers: Operations.BookControllerGetFileProgress.Input.Headers = .init()
    ) async throws -> Operations.BookControllerGetFileProgress.Output {
        try await bookControllerGetFileProgress(Operations.BookControllerGetFileProgress.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /api/v1/books/files/{fileId}/progress`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/post(BookController_saveFileProgress)`.
    public func bookControllerSaveFileProgress(
        path: Operations.BookControllerSaveFileProgress.Input.Path,
        body: Operations.BookControllerSaveFileProgress.Input.Body
    ) async throws -> Operations.BookControllerSaveFileProgress.Output {
        try await bookControllerSaveFileProgress(Operations.BookControllerSaveFileProgress.Input(
            path: path,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/books/files/{fileId}/sessions`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/sessions/post(ReadingSessionController_saveSession)`.
    public func readingSessionControllerSaveSession(
        path: Operations.ReadingSessionControllerSaveSession.Input.Path,
        body: Operations.ReadingSessionControllerSaveSession.Input.Body
    ) async throws -> Operations.ReadingSessionControllerSaveSession.Output {
        try await readingSessionControllerSaveSession(Operations.ReadingSessionControllerSaveSession.Input(
            path: path,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/books/{bookId}/bookmarks`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/get(BookmarkController_getBookmarks)`.
    public func bookmarkControllerGetBookmarks(
        path: Operations.BookmarkControllerGetBookmarks.Input.Path,
        headers: Operations.BookmarkControllerGetBookmarks.Input.Headers = .init()
    ) async throws -> Operations.BookmarkControllerGetBookmarks.Output {
        try await bookmarkControllerGetBookmarks(Operations.BookmarkControllerGetBookmarks.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /api/v1/books/{bookId}/bookmarks`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/post(BookmarkController_createBookmark)`.
    public func bookmarkControllerCreateBookmark(
        path: Operations.BookmarkControllerCreateBookmark.Input.Path,
        headers: Operations.BookmarkControllerCreateBookmark.Input.Headers = .init(),
        body: Operations.BookmarkControllerCreateBookmark.Input.Body
    ) async throws -> Operations.BookmarkControllerCreateBookmark.Output {
        try await bookmarkControllerCreateBookmark(Operations.BookmarkControllerCreateBookmark.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /api/v1/books/{bookId}/bookmarks/{bookmarkId}`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/{bookmarkId}/delete(BookmarkController_deleteBookmark)`.
    public func bookmarkControllerDeleteBookmark(path: Operations.BookmarkControllerDeleteBookmark.Input.Path) async throws -> Operations.BookmarkControllerDeleteBookmark.Output {
        try await bookmarkControllerDeleteBookmark(Operations.BookmarkControllerDeleteBookmark.Input(path: path))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {}
