// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/LoginDto`.
        public struct LoginDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LoginDto/username`.
            public var username: Swift.String
            /// - Remark: Generated from `#/components/schemas/LoginDto/password`.
            public var password: Swift.String
            /// - Remark: Generated from `#/components/schemas/LoginDto/clientKind`.
            @frozen public enum ClientKindPayload: String, Codable, Hashable, Sendable, CaseIterable {
                case web = "web"
                case native = "native"
            }
            /// - Remark: Generated from `#/components/schemas/LoginDto/clientKind`.
            public var clientKind: Components.Schemas.LoginDto.ClientKindPayload?
            /// - Remark: Generated from `#/components/schemas/LoginDto/deviceLabel`.
            public var deviceLabel: Swift.String?
            /// Creates a new `LoginDto`.
            ///
            /// - Parameters:
            ///   - username:
            ///   - password:
            ///   - clientKind:
            ///   - deviceLabel:
            public init(
                username: Swift.String,
                password: Swift.String,
                clientKind: Components.Schemas.LoginDto.ClientKindPayload? = nil,
                deviceLabel: Swift.String? = nil
            ) {
                self.username = username
                self.password = password
                self.clientKind = clientKind
                self.deviceLabel = deviceLabel
            }
            public enum CodingKeys: String, CodingKey {
                case username
                case password
                case clientKind
                case deviceLabel
            }
        }
        /// - Remark: Generated from `#/components/schemas/RefreshDto`.
        public struct RefreshDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/RefreshDto/refreshToken`.
            public var refreshToken: Swift.String?
            /// Creates a new `RefreshDto`.
            ///
            /// - Parameters:
            ///   - refreshToken:
            public init(refreshToken: Swift.String? = nil) {
                self.refreshToken = refreshToken
            }
            public enum CodingKeys: String, CodingKey {
                case refreshToken
            }
        }
        /// - Remark: Generated from `#/components/schemas/LogoutDto`.
        public struct LogoutDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LogoutDto/refreshToken`.
            public var refreshToken: Swift.String?
            /// Creates a new `LogoutDto`.
            ///
            /// - Parameters:
            ///   - refreshToken:
            public init(refreshToken: Swift.String? = nil) {
                self.refreshToken = refreshToken
            }
            public enum CodingKeys: String, CodingKey {
                case refreshToken
            }
        }
        /// - Remark: Generated from `#/components/schemas/SaveProgressDto`.
        public struct SaveProgressDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/source`.
            @frozen public enum SourcePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case text = "text"
                case narration = "narration"
            }
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/source`.
            public var source: Components.Schemas.SaveProgressDto.SourcePayload?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/cfi`.
            public var cfi: Swift.String?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/pageNumber`.
            public var pageNumber: Swift.Double?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/percentage`.
            public var percentage: Swift.Double
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/positionSeconds`.
            public var positionSeconds: Swift.Double?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/mediaOverlayFragment`.
            public var mediaOverlayFragment: Swift.String?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/mediaOverlaySectionIndex`.
            public var mediaOverlaySectionIndex: Swift.Double?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/koboLocationSource`.
            public var koboLocationSource: Swift.String?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/koboLocationType`.
            public var koboLocationType: Swift.String?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/koboLocationValue`.
            public var koboLocationValue: Swift.String?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/koreaderProgress`.
            public var koreaderProgress: Swift.String?
            /// - Remark: Generated from `#/components/schemas/SaveProgressDto/koboContentSourceProgressPercent`.
            public var koboContentSourceProgressPercent: Swift.Double?
            /// Creates a new `SaveProgressDto`.
            ///
            /// - Parameters:
            ///   - source:
            ///   - cfi:
            ///   - pageNumber:
            ///   - percentage:
            ///   - positionSeconds:
            ///   - mediaOverlayFragment:
            ///   - mediaOverlaySectionIndex:
            ///   - koboLocationSource:
            ///   - koboLocationType:
            ///   - koboLocationValue:
            ///   - koreaderProgress:
            ///   - koboContentSourceProgressPercent:
            public init(
                source: Components.Schemas.SaveProgressDto.SourcePayload? = nil,
                cfi: Swift.String? = nil,
                pageNumber: Swift.Double? = nil,
                percentage: Swift.Double,
                positionSeconds: Swift.Double? = nil,
                mediaOverlayFragment: Swift.String? = nil,
                mediaOverlaySectionIndex: Swift.Double? = nil,
                koboLocationSource: Swift.String? = nil,
                koboLocationType: Swift.String? = nil,
                koboLocationValue: Swift.String? = nil,
                koreaderProgress: Swift.String? = nil,
                koboContentSourceProgressPercent: Swift.Double? = nil
            ) {
                self.source = source
                self.cfi = cfi
                self.pageNumber = pageNumber
                self.percentage = percentage
                self.positionSeconds = positionSeconds
                self.mediaOverlayFragment = mediaOverlayFragment
                self.mediaOverlaySectionIndex = mediaOverlaySectionIndex
                self.koboLocationSource = koboLocationSource
                self.koboLocationType = koboLocationType
                self.koboLocationValue = koboLocationValue
                self.koreaderProgress = koreaderProgress
                self.koboContentSourceProgressPercent = koboContentSourceProgressPercent
            }
            public enum CodingKeys: String, CodingKey {
                case source
                case cfi
                case pageNumber
                case percentage
                case positionSeconds
                case mediaOverlayFragment
                case mediaOverlaySectionIndex
                case koboLocationSource
                case koboLocationType
                case koboLocationValue
                case koreaderProgress
                case koboContentSourceProgressPercent
            }
        }
        /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto`.
        public struct SaveReadingSessionDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/sessionId`.
            public var sessionId: Swift.String
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/startedAt`.
            public var startedAt: Swift.String
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/endedAt`.
            public var endedAt: Swift.String
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/durationSeconds`.
            public var durationSeconds: Swift.Double
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/progressDelta`.
            public var progressDelta: Swift.Double?
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/endProgress`.
            public var endProgress: Swift.Double?
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/sessionType`.
            @frozen public enum SessionTypePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case read = "read"
                case tts = "tts"
                case listen = "listen"
            }
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/sessionType`.
            public var sessionType: Components.Schemas.SaveReadingSessionDto.SessionTypePayload?
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/source`.
            @frozen public enum SourcePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case ios = "ios"
                case watchos = "watchos"
                case android = "android"
            }
            /// - Remark: Generated from `#/components/schemas/SaveReadingSessionDto/source`.
            public var source: Components.Schemas.SaveReadingSessionDto.SourcePayload?
            /// Creates a new `SaveReadingSessionDto`.
            ///
            /// - Parameters:
            ///   - sessionId:
            ///   - startedAt:
            ///   - endedAt:
            ///   - durationSeconds:
            ///   - progressDelta:
            ///   - endProgress:
            ///   - sessionType:
            ///   - source:
            public init(
                sessionId: Swift.String,
                startedAt: Swift.String,
                endedAt: Swift.String,
                durationSeconds: Swift.Double,
                progressDelta: Swift.Double? = nil,
                endProgress: Swift.Double? = nil,
                sessionType: Components.Schemas.SaveReadingSessionDto.SessionTypePayload? = nil,
                source: Components.Schemas.SaveReadingSessionDto.SourcePayload? = nil
            ) {
                self.sessionId = sessionId
                self.startedAt = startedAt
                self.endedAt = endedAt
                self.durationSeconds = durationSeconds
                self.progressDelta = progressDelta
                self.endProgress = endProgress
                self.sessionType = sessionType
                self.source = source
            }
            public enum CodingKeys: String, CodingKey {
                case sessionId
                case startedAt
                case endedAt
                case durationSeconds
                case progressDelta
                case endProgress
                case sessionType
                case source
            }
        }
        /// - Remark: Generated from `#/components/schemas/BookmarkResponseDto`.
        public struct BookmarkResponseDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BookmarkResponseDto/id`.
            public var id: Swift.Double
            /// - Remark: Generated from `#/components/schemas/BookmarkResponseDto/bookId`.
            public var bookId: Swift.Double
            /// - Remark: Generated from `#/components/schemas/BookmarkResponseDto/cfi`.
            public var cfi: Swift.String?
            /// - Remark: Generated from `#/components/schemas/BookmarkResponseDto/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/BookmarkResponseDto/positionSeconds`.
            public var positionSeconds: Swift.Double?
            /// - Remark: Generated from `#/components/schemas/BookmarkResponseDto/createdAt`.
            public var createdAt: Foundation.Date
            /// Creates a new `BookmarkResponseDto`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - bookId:
            ///   - cfi:
            ///   - title:
            ///   - positionSeconds:
            ///   - createdAt:
            public init(
                id: Swift.Double,
                bookId: Swift.Double,
                cfi: Swift.String? = nil,
                title: Swift.String,
                positionSeconds: Swift.Double? = nil,
                createdAt: Foundation.Date
            ) {
                self.id = id
                self.bookId = bookId
                self.cfi = cfi
                self.title = title
                self.positionSeconds = positionSeconds
                self.createdAt = createdAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case bookId
                case cfi
                case title
                case positionSeconds
                case createdAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/CreateBookmarkDto`.
        public struct CreateBookmarkDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/CreateBookmarkDto/cfi`.
            public var cfi: Swift.String
            /// - Remark: Generated from `#/components/schemas/CreateBookmarkDto/title`.
            public var title: Swift.String
            /// Creates a new `CreateBookmarkDto`.
            ///
            /// - Parameters:
            ///   - cfi:
            ///   - title:
            public init(
                cfi: Swift.String,
                title: Swift.String
            ) {
                self.cfi = cfi
                self.title = title
            }
            public enum CodingKeys: String, CodingKey {
                case cfi
                case title
            }
        }
        /// - Remark: Generated from `#/components/schemas/OidcProviderSummary`.
        public struct OidcProviderSummary: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/OidcProviderSummary/slug`.
            public var slug: Swift.String
            /// - Remark: Generated from `#/components/schemas/OidcProviderSummary/displayName`.
            public var displayName: Swift.String
            /// - Remark: Generated from `#/components/schemas/OidcProviderSummary/iconUrl`.
            public var iconUrl: Swift.String?
            /// Creates a new `OidcProviderSummary`.
            ///
            /// - Parameters:
            ///   - slug:
            ///   - displayName:
            ///   - iconUrl:
            public init(
                slug: Swift.String,
                displayName: Swift.String,
                iconUrl: Swift.String? = nil
            ) {
                self.slug = slug
                self.displayName = displayName
                self.iconUrl = iconUrl
            }
            public enum CodingKeys: String, CodingKey {
                case slug
                case displayName
                case iconUrl
            }
        }
        /// - Remark: Generated from `#/components/schemas/LoginOptions`.
        public struct LoginOptions: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LoginOptions/passwordLoginEnabled`.
            public var passwordLoginEnabled: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/LoginOptions/allowRegistration`.
            public var allowRegistration: Swift.Bool?
            /// - Remark: Generated from `#/components/schemas/LoginOptions/oidcProviders`.
            public var oidcProviders: [Components.Schemas.OidcProviderSummary]
            /// Creates a new `LoginOptions`.
            ///
            /// - Parameters:
            ///   - passwordLoginEnabled:
            ///   - allowRegistration:
            ///   - oidcProviders:
            public init(
                passwordLoginEnabled: Swift.Bool,
                allowRegistration: Swift.Bool? = nil,
                oidcProviders: [Components.Schemas.OidcProviderSummary]
            ) {
                self.passwordLoginEnabled = passwordLoginEnabled
                self.allowRegistration = allowRegistration
                self.oidcProviders = oidcProviders
            }
            public enum CodingKeys: String, CodingKey {
                case passwordLoginEnabled
                case allowRegistration
                case oidcProviders
            }
        }
        /// - Remark: Generated from `#/components/schemas/AuthUser`.
        public struct AuthUser: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/AuthUser/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/AuthUser/username`.
            public var username: Swift.String
            /// - Remark: Generated from `#/components/schemas/AuthUser/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/AuthUser/email`.
            public var email: Swift.String?
            /// - Remark: Generated from `#/components/schemas/AuthUser/isSuperuser`.
            public var isSuperuser: Swift.Bool?
            /// - Remark: Generated from `#/components/schemas/AuthUser/permissions`.
            public var permissions: [Swift.String]?
            /// Creates a new `AuthUser`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - username:
            ///   - name:
            ///   - email:
            ///   - isSuperuser:
            ///   - permissions:
            public init(
                id: Swift.Int,
                username: Swift.String,
                name: Swift.String,
                email: Swift.String? = nil,
                isSuperuser: Swift.Bool? = nil,
                permissions: [Swift.String]? = nil
            ) {
                self.id = id
                self.username = username
                self.name = name
                self.email = email
                self.isSuperuser = isSuperuser
                self.permissions = permissions
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case username
                case name
                case email
                case isSuperuser
                case permissions
            }
        }
        /// - Remark: Generated from `#/components/schemas/NativeCredentials`.
        public struct NativeCredentials: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/accessToken`.
            public var accessToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/accessTokenExpiresAt`.
            public var accessTokenExpiresAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/refreshToken`.
            public var refreshToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/refreshTokenExpiresAt`.
            public var refreshTokenExpiresAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/sessionId`.
            public var sessionId: Swift.Int
            /// Creates a new `NativeCredentials`.
            ///
            /// - Parameters:
            ///   - accessToken:
            ///   - accessTokenExpiresAt:
            ///   - refreshToken:
            ///   - refreshTokenExpiresAt:
            ///   - sessionId:
            public init(
                accessToken: Swift.String,
                accessTokenExpiresAt: Foundation.Date,
                refreshToken: Swift.String,
                refreshTokenExpiresAt: Foundation.Date,
                sessionId: Swift.Int
            ) {
                self.accessToken = accessToken
                self.accessTokenExpiresAt = accessTokenExpiresAt
                self.refreshToken = refreshToken
                self.refreshTokenExpiresAt = refreshTokenExpiresAt
                self.sessionId = sessionId
            }
            public enum CodingKeys: String, CodingKey {
                case accessToken
                case accessTokenExpiresAt
                case refreshToken
                case refreshTokenExpiresAt
                case sessionId
            }
        }
        /// - Remark: Generated from `#/components/schemas/NativeAuthResponse`.
        public struct NativeAuthResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/accessToken`.
            public var accessToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/accessTokenExpiresAt`.
            public var accessTokenExpiresAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/refreshToken`.
            public var refreshToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/refreshTokenExpiresAt`.
            public var refreshTokenExpiresAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/sessionId`.
            public var sessionId: Swift.Int
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/user`.
            public var user: Components.Schemas.AuthUser
            /// Creates a new `NativeAuthResponse`.
            ///
            /// - Parameters:
            ///   - accessToken:
            ///   - accessTokenExpiresAt:
            ///   - refreshToken:
            ///   - refreshTokenExpiresAt:
            ///   - sessionId:
            ///   - user:
            public init(
                accessToken: Swift.String,
                accessTokenExpiresAt: Foundation.Date,
                refreshToken: Swift.String,
                refreshTokenExpiresAt: Foundation.Date,
                sessionId: Swift.Int,
                user: Components.Schemas.AuthUser
            ) {
                self.accessToken = accessToken
                self.accessTokenExpiresAt = accessTokenExpiresAt
                self.refreshToken = refreshToken
                self.refreshTokenExpiresAt = refreshTokenExpiresAt
                self.sessionId = sessionId
                self.user = user
            }
            public enum CodingKeys: String, CodingKey {
                case accessToken
                case accessTokenExpiresAt
                case refreshToken
                case refreshTokenExpiresAt
                case sessionId
                case user
            }
        }
        /// - Remark: Generated from `#/components/schemas/ApiError`.
        public struct ApiError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ApiError/statusCode`.
            public var statusCode: Swift.Int
            /// - Remark: Generated from `#/components/schemas/ApiError/message`.
            public var message: Swift.String
            /// - Remark: Generated from `#/components/schemas/ApiError/errorCode`.
            public var errorCode: Swift.String?
            /// - Remark: Generated from `#/components/schemas/ApiError/retryAfterSeconds`.
            public var retryAfterSeconds: Swift.Int?
            /// Creates a new `ApiError`.
            ///
            /// - Parameters:
            ///   - statusCode:
            ///   - message:
            ///   - errorCode:
            ///   - retryAfterSeconds:
            public init(
                statusCode: Swift.Int,
                message: Swift.String,
                errorCode: Swift.String? = nil,
                retryAfterSeconds: Swift.Int? = nil
            ) {
                self.statusCode = statusCode
                self.message = message
                self.errorCode = errorCode
                self.retryAfterSeconds = retryAfterSeconds
            }
            public enum CodingKeys: String, CodingKey {
                case statusCode
                case message
                case errorCode
                case retryAfterSeconds
            }
        }
        /// - Remark: Generated from `#/components/schemas/SortSpec`.
        public struct SortSpec: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SortSpec/field`.
            public var field: Swift.String
            /// - Remark: Generated from `#/components/schemas/SortSpec/dir`.
            @frozen public enum DirPayload: String, Codable, Hashable, Sendable, CaseIterable {
                case asc = "asc"
                case desc = "desc"
            }
            /// - Remark: Generated from `#/components/schemas/SortSpec/dir`.
            public var dir: Components.Schemas.SortSpec.DirPayload
            /// Creates a new `SortSpec`.
            ///
            /// - Parameters:
            ///   - field:
            ///   - dir:
            public init(
                field: Swift.String,
                dir: Components.Schemas.SortSpec.DirPayload
            ) {
                self.field = field
                self.dir = dir
            }
            public enum CodingKeys: String, CodingKey {
                case field
                case dir
            }
        }
        /// - Remark: Generated from `#/components/schemas/BookQuery`.
        public struct BookQuery: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BookQuery/sort`.
            public var sort: [Components.Schemas.SortSpec]
            /// - Remark: Generated from `#/components/schemas/BookQuery/pagination`.
            public struct PaginationPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BookQuery/pagination/page`.
                public var page: Swift.Int
                /// - Remark: Generated from `#/components/schemas/BookQuery/pagination/size`.
                public var size: Swift.Int
                /// Creates a new `PaginationPayload`.
                ///
                /// - Parameters:
                ///   - page:
                ///   - size:
                public init(
                    page: Swift.Int,
                    size: Swift.Int
                ) {
                    self.page = page
                    self.size = size
                }
                public enum CodingKeys: String, CodingKey {
                    case page
                    case size
                }
            }
            /// - Remark: Generated from `#/components/schemas/BookQuery/pagination`.
            public var pagination: Components.Schemas.BookQuery.PaginationPayload
            /// - Remark: Generated from `#/components/schemas/BookQuery/q`.
            public var q: Swift.String?
            /// Creates a new `BookQuery`.
            ///
            /// - Parameters:
            ///   - sort:
            ///   - pagination:
            ///   - q:
            public init(
                sort: [Components.Schemas.SortSpec],
                pagination: Components.Schemas.BookQuery.PaginationPayload,
                q: Swift.String? = nil
            ) {
                self.sort = sort
                self.pagination = pagination
                self.q = q
            }
            public enum CodingKeys: String, CodingKey {
                case sort
                case pagination
                case q
            }
        }
        /// - Remark: Generated from `#/components/schemas/BookFileRef`.
        public struct BookFileRef: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BookFileRef/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BookFileRef/format`.
            public var format: Swift.String?
            /// - Remark: Generated from `#/components/schemas/BookFileRef/role`.
            public var role: Swift.String
            /// Creates a new `BookFileRef`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - format:
            ///   - role:
            public init(
                id: Swift.Int,
                format: Swift.String? = nil,
                role: Swift.String
            ) {
                self.id = id
                self.format = format
                self.role = role
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case format
                case role
            }
        }
        /// - Remark: Generated from `#/components/schemas/BookCard`.
        public struct BookCard: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BookCard/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BookCard/title`.
            public var title: Swift.String?
            /// - Remark: Generated from `#/components/schemas/BookCard/authors`.
            public var authors: [Swift.String]
            /// - Remark: Generated from `#/components/schemas/BookCard/hasCover`.
            public var hasCover: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/BookCard/coverVersion`.
            public var coverVersion: Swift.String
            /// - Remark: Generated from `#/components/schemas/BookCard/files`.
            public var files: [Components.Schemas.BookFileRef]
            /// Creates a new `BookCard`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - authors:
            ///   - hasCover:
            ///   - coverVersion:
            ///   - files:
            public init(
                id: Swift.Int,
                title: Swift.String? = nil,
                authors: [Swift.String],
                hasCover: Swift.Bool,
                coverVersion: Swift.String,
                files: [Components.Schemas.BookFileRef]
            ) {
                self.id = id
                self.title = title
                self.authors = authors
                self.hasCover = hasCover
                self.coverVersion = coverVersion
                self.files = files
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case authors
                case hasCover
                case coverVersion
                case files
            }
        }
        /// - Remark: Generated from `#/components/schemas/BooksPage`.
        public struct BooksPage: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BooksPage/items`.
            public var items: [Components.Schemas.BookCard]
            /// - Remark: Generated from `#/components/schemas/BooksPage/total`.
            public var total: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BooksPage/page`.
            public var page: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BooksPage/size`.
            public var size: Swift.Int
            /// Creates a new `BooksPage`.
            ///
            /// - Parameters:
            ///   - items:
            ///   - total:
            ///   - page:
            ///   - size:
            public init(
                items: [Components.Schemas.BookCard],
                total: Swift.Int,
                page: Swift.Int,
                size: Swift.Int
            ) {
                self.items = items
                self.total = total
                self.page = page
                self.size = size
            }
            public enum CodingKeys: String, CodingKey {
                case items
                case total
                case page
                case size
            }
        }
        /// - Remark: Generated from `#/components/schemas/FileProgress`.
        public struct FileProgress: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/FileProgress/cfi`.
            public var cfi: Swift.String?
            /// - Remark: Generated from `#/components/schemas/FileProgress/pageNumber`.
            public var pageNumber: Swift.Int?
            /// - Remark: Generated from `#/components/schemas/FileProgress/percentage`.
            public var percentage: Swift.Double
            /// - Remark: Generated from `#/components/schemas/FileProgress/positionSeconds`.
            public var positionSeconds: Swift.Double?
            /// Creates a new `FileProgress`.
            ///
            /// - Parameters:
            ///   - cfi:
            ///   - pageNumber:
            ///   - percentage:
            ///   - positionSeconds:
            public init(
                cfi: Swift.String? = nil,
                pageNumber: Swift.Int? = nil,
                percentage: Swift.Double,
                positionSeconds: Swift.Double? = nil
            ) {
                self.cfi = cfi
                self.pageNumber = pageNumber
                self.percentage = percentage
                self.positionSeconds = positionSeconds
            }
            public enum CodingKeys: String, CodingKey {
                case cfi
                case pageNumber
                case percentage
                case positionSeconds
            }
        }
    }
}
