// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/LoginDto`.
        public struct LoginDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LoginDto/username`.
            public var username: Swift.String
            /// - Remark: Generated from `#/components/schemas/LoginDto/password`.
            public var password: Swift.String
            /// - Remark: Generated from `#/components/schemas/LoginDto/clientKind`.
            @frozen public enum ClientKindPayload: String, Codable, Hashable, Sendable, CaseIterable {
                case web = "web"
                case native = "native"
            }
            /// - Remark: Generated from `#/components/schemas/LoginDto/clientKind`.
            public var clientKind: Components.Schemas.LoginDto.ClientKindPayload?
            /// - Remark: Generated from `#/components/schemas/LoginDto/deviceLabel`.
            public var deviceLabel: Swift.String?
            /// Creates a new `LoginDto`.
            ///
            /// - Parameters:
            ///   - username:
            ///   - password:
            ///   - clientKind:
            ///   - deviceLabel:
            public init(
                username: Swift.String,
                password: Swift.String,
                clientKind: Components.Schemas.LoginDto.ClientKindPayload? = nil,
                deviceLabel: Swift.String? = nil
            ) {
                self.username = username
                self.password = password
                self.clientKind = clientKind
                self.deviceLabel = deviceLabel
            }
            public enum CodingKeys: String, CodingKey {
                case username
                case password
                case clientKind
                case deviceLabel
            }
        }
        /// - Remark: Generated from `#/components/schemas/RefreshDto`.
        public struct RefreshDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/RefreshDto/refreshToken`.
            public var refreshToken: Swift.String?
            /// Creates a new `RefreshDto`.
            ///
            /// - Parameters:
            ///   - refreshToken:
            public init(refreshToken: Swift.String? = nil) {
                self.refreshToken = refreshToken
            }
            public enum CodingKeys: String, CodingKey {
                case refreshToken
            }
        }
        /// - Remark: Generated from `#/components/schemas/LogoutDto`.
        public struct LogoutDto: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LogoutDto/refreshToken`.
            public var refreshToken: Swift.String?
            /// Creates a new `LogoutDto`.
            ///
            /// - Parameters:
            ///   - refreshToken:
            public init(refreshToken: Swift.String? = nil) {
                self.refreshToken = refreshToken
            }
            public enum CodingKeys: String, CodingKey {
                case refreshToken
            }
        }
        /// - Remark: Generated from `#/components/schemas/ApiError`.
        public struct ApiError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ApiError/statusCode`.
            public var statusCode: Swift.Int
            /// - Remark: Generated from `#/components/schemas/ApiError/message`.
            public var message: Swift.String
            /// - Remark: Generated from `#/components/schemas/ApiError/errorCode`.
            public var errorCode: Swift.String?
            /// - Remark: Generated from `#/components/schemas/ApiError/retryAfterSeconds`.
            public var retryAfterSeconds: Swift.Int?
            /// Creates a new `ApiError`.
            ///
            /// - Parameters:
            ///   - statusCode:
            ///   - message:
            ///   - errorCode:
            ///   - retryAfterSeconds:
            public init(
                statusCode: Swift.Int,
                message: Swift.String,
                errorCode: Swift.String? = nil,
                retryAfterSeconds: Swift.Int? = nil
            ) {
                self.statusCode = statusCode
                self.message = message
                self.errorCode = errorCode
                self.retryAfterSeconds = retryAfterSeconds
            }
            public enum CodingKeys: String, CodingKey {
                case statusCode
                case message
                case errorCode
                case retryAfterSeconds
            }
        }
        /// - Remark: Generated from `#/components/schemas/OidcProviderSummary`.
        public struct OidcProviderSummary: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/OidcProviderSummary/slug`.
            public var slug: Swift.String
            /// - Remark: Generated from `#/components/schemas/OidcProviderSummary/displayName`.
            public var displayName: Swift.String
            /// - Remark: Generated from `#/components/schemas/OidcProviderSummary/iconUrl`.
            public var iconUrl: Swift.String?
            /// Creates a new `OidcProviderSummary`.
            ///
            /// - Parameters:
            ///   - slug:
            ///   - displayName:
            ///   - iconUrl:
            public init(
                slug: Swift.String,
                displayName: Swift.String,
                iconUrl: Swift.String? = nil
            ) {
                self.slug = slug
                self.displayName = displayName
                self.iconUrl = iconUrl
            }
            public enum CodingKeys: String, CodingKey {
                case slug
                case displayName
                case iconUrl
            }
        }
        /// - Remark: Generated from `#/components/schemas/LoginOptions`.
        public struct LoginOptions: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LoginOptions/passwordLoginEnabled`.
            public var passwordLoginEnabled: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/LoginOptions/allowRegistration`.
            public var allowRegistration: Swift.Bool?
            /// - Remark: Generated from `#/components/schemas/LoginOptions/oidcProviders`.
            public var oidcProviders: [Components.Schemas.OidcProviderSummary]
            /// Creates a new `LoginOptions`.
            ///
            /// - Parameters:
            ///   - passwordLoginEnabled:
            ///   - allowRegistration:
            ///   - oidcProviders:
            public init(
                passwordLoginEnabled: Swift.Bool,
                allowRegistration: Swift.Bool? = nil,
                oidcProviders: [Components.Schemas.OidcProviderSummary]
            ) {
                self.passwordLoginEnabled = passwordLoginEnabled
                self.allowRegistration = allowRegistration
                self.oidcProviders = oidcProviders
            }
            public enum CodingKeys: String, CodingKey {
                case passwordLoginEnabled
                case allowRegistration
                case oidcProviders
            }
        }
        /// - Remark: Generated from `#/components/schemas/AuthUser`.
        public struct AuthUser: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/AuthUser/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/AuthUser/username`.
            public var username: Swift.String
            /// - Remark: Generated from `#/components/schemas/AuthUser/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/AuthUser/email`.
            public var email: Swift.String?
            /// - Remark: Generated from `#/components/schemas/AuthUser/isSuperuser`.
            public var isSuperuser: Swift.Bool?
            /// - Remark: Generated from `#/components/schemas/AuthUser/permissions`.
            public var permissions: [Swift.String]?
            /// Creates a new `AuthUser`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - username:
            ///   - name:
            ///   - email:
            ///   - isSuperuser:
            ///   - permissions:
            public init(
                id: Swift.Int,
                username: Swift.String,
                name: Swift.String,
                email: Swift.String? = nil,
                isSuperuser: Swift.Bool? = nil,
                permissions: [Swift.String]? = nil
            ) {
                self.id = id
                self.username = username
                self.name = name
                self.email = email
                self.isSuperuser = isSuperuser
                self.permissions = permissions
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case username
                case name
                case email
                case isSuperuser
                case permissions
            }
        }
        /// - Remark: Generated from `#/components/schemas/NativeCredentials`.
        public struct NativeCredentials: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/accessToken`.
            public var accessToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/accessTokenExpiresAt`.
            public var accessTokenExpiresAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/refreshToken`.
            public var refreshToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/refreshTokenExpiresAt`.
            public var refreshTokenExpiresAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/NativeCredentials/sessionId`.
            public var sessionId: Swift.Int
            /// Creates a new `NativeCredentials`.
            ///
            /// - Parameters:
            ///   - accessToken:
            ///   - accessTokenExpiresAt:
            ///   - refreshToken:
            ///   - refreshTokenExpiresAt:
            ///   - sessionId:
            public init(
                accessToken: Swift.String,
                accessTokenExpiresAt: Foundation.Date,
                refreshToken: Swift.String,
                refreshTokenExpiresAt: Foundation.Date,
                sessionId: Swift.Int
            ) {
                self.accessToken = accessToken
                self.accessTokenExpiresAt = accessTokenExpiresAt
                self.refreshToken = refreshToken
                self.refreshTokenExpiresAt = refreshTokenExpiresAt
                self.sessionId = sessionId
            }
            public enum CodingKeys: String, CodingKey {
                case accessToken
                case accessTokenExpiresAt
                case refreshToken
                case refreshTokenExpiresAt
                case sessionId
            }
        }
        /// - Remark: Generated from `#/components/schemas/NativeAuthResponse`.
        public struct NativeAuthResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/accessToken`.
            public var accessToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/accessTokenExpiresAt`.
            public var accessTokenExpiresAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/refreshToken`.
            public var refreshToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/refreshTokenExpiresAt`.
            public var refreshTokenExpiresAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/sessionId`.
            public var sessionId: Swift.Int
            /// - Remark: Generated from `#/components/schemas/NativeAuthResponse/user`.
            public var user: Components.Schemas.AuthUser
            /// Creates a new `NativeAuthResponse`.
            ///
            /// - Parameters:
            ///   - accessToken:
            ///   - accessTokenExpiresAt:
            ///   - refreshToken:
            ///   - refreshTokenExpiresAt:
            ///   - sessionId:
            ///   - user:
            public init(
                accessToken: Swift.String,
                accessTokenExpiresAt: Foundation.Date,
                refreshToken: Swift.String,
                refreshTokenExpiresAt: Foundation.Date,
                sessionId: Swift.Int,
                user: Components.Schemas.AuthUser
            ) {
                self.accessToken = accessToken
                self.accessTokenExpiresAt = accessTokenExpiresAt
                self.refreshToken = refreshToken
                self.refreshTokenExpiresAt = refreshTokenExpiresAt
                self.sessionId = sessionId
                self.user = user
            }
            public enum CodingKeys: String, CodingKey {
                case accessToken
                case accessTokenExpiresAt
                case refreshToken
                case refreshTokenExpiresAt
                case sessionId
                case user
            }
        }
        /// - Remark: Generated from `#/components/schemas/SortSpec`.
        public struct SortSpec: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SortSpec/field`.
            public var field: Swift.String
            /// - Remark: Generated from `#/components/schemas/SortSpec/dir`.
            @frozen public enum DirPayload: String, Codable, Hashable, Sendable, CaseIterable {
                case asc = "asc"
                case desc = "desc"
            }
            /// - Remark: Generated from `#/components/schemas/SortSpec/dir`.
            public var dir: Components.Schemas.SortSpec.DirPayload
            /// Creates a new `SortSpec`.
            ///
            /// - Parameters:
            ///   - field:
            ///   - dir:
            public init(
                field: Swift.String,
                dir: Components.Schemas.SortSpec.DirPayload
            ) {
                self.field = field
                self.dir = dir
            }
            public enum CodingKeys: String, CodingKey {
                case field
                case dir
            }
        }
        /// - Remark: Generated from `#/components/schemas/BookQuery`.
        public struct BookQuery: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BookQuery/sort`.
            public var sort: [Components.Schemas.SortSpec]
            /// - Remark: Generated from `#/components/schemas/BookQuery/pagination`.
            public struct PaginationPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BookQuery/pagination/page`.
                public var page: Swift.Int
                /// - Remark: Generated from `#/components/schemas/BookQuery/pagination/size`.
                public var size: Swift.Int
                /// Creates a new `PaginationPayload`.
                ///
                /// - Parameters:
                ///   - page:
                ///   - size:
                public init(
                    page: Swift.Int,
                    size: Swift.Int
                ) {
                    self.page = page
                    self.size = size
                }
                public enum CodingKeys: String, CodingKey {
                    case page
                    case size
                }
            }
            /// - Remark: Generated from `#/components/schemas/BookQuery/pagination`.
            public var pagination: Components.Schemas.BookQuery.PaginationPayload
            /// - Remark: Generated from `#/components/schemas/BookQuery/q`.
            public var q: Swift.String?
            /// Creates a new `BookQuery`.
            ///
            /// - Parameters:
            ///   - sort:
            ///   - pagination:
            ///   - q:
            public init(
                sort: [Components.Schemas.SortSpec],
                pagination: Components.Schemas.BookQuery.PaginationPayload,
                q: Swift.String? = nil
            ) {
                self.sort = sort
                self.pagination = pagination
                self.q = q
            }
            public enum CodingKeys: String, CodingKey {
                case sort
                case pagination
                case q
            }
        }
        /// - Remark: Generated from `#/components/schemas/BookFileRef`.
        public struct BookFileRef: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BookFileRef/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BookFileRef/format`.
            public var format: Swift.String?
            /// - Remark: Generated from `#/components/schemas/BookFileRef/role`.
            public var role: Swift.String
            /// Creates a new `BookFileRef`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - format:
            ///   - role:
            public init(
                id: Swift.Int,
                format: Swift.String? = nil,
                role: Swift.String
            ) {
                self.id = id
                self.format = format
                self.role = role
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case format
                case role
            }
        }
        /// - Remark: Generated from `#/components/schemas/BookCard`.
        public struct BookCard: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BookCard/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BookCard/title`.
            public var title: Swift.String?
            /// - Remark: Generated from `#/components/schemas/BookCard/authors`.
            public var authors: [Swift.String]
            /// - Remark: Generated from `#/components/schemas/BookCard/hasCover`.
            public var hasCover: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/BookCard/coverVersion`.
            public var coverVersion: Swift.String
            /// - Remark: Generated from `#/components/schemas/BookCard/files`.
            public var files: [Components.Schemas.BookFileRef]
            /// Creates a new `BookCard`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - authors:
            ///   - hasCover:
            ///   - coverVersion:
            ///   - files:
            public init(
                id: Swift.Int,
                title: Swift.String? = nil,
                authors: [Swift.String],
                hasCover: Swift.Bool,
                coverVersion: Swift.String,
                files: [Components.Schemas.BookFileRef]
            ) {
                self.id = id
                self.title = title
                self.authors = authors
                self.hasCover = hasCover
                self.coverVersion = coverVersion
                self.files = files
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case authors
                case hasCover
                case coverVersion
                case files
            }
        }
        /// - Remark: Generated from `#/components/schemas/BooksPage`.
        public struct BooksPage: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BooksPage/items`.
            public var items: [Components.Schemas.BookCard]
            /// - Remark: Generated from `#/components/schemas/BooksPage/total`.
            public var total: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BooksPage/page`.
            public var page: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BooksPage/size`.
            public var size: Swift.Int
            /// Creates a new `BooksPage`.
            ///
            /// - Parameters:
            ///   - items:
            ///   - total:
            ///   - page:
            ///   - size:
            public init(
                items: [Components.Schemas.BookCard],
                total: Swift.Int,
                page: Swift.Int,
                size: Swift.Int
            ) {
                self.items = items
                self.total = total
                self.page = page
                self.size = size
            }
            public enum CodingKeys: String, CodingKey {
                case items
                case total
                case page
                case size
            }
        }
    }
}
