// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// - Remark: HTTP `GET /api/v1/auth/login-options`.
    /// - Remark: Generated from `#/paths//api/v1/auth/login-options/get(AuthController_loginOptions)`.
    public enum AuthControllerLoginOptions {
        public static let id: Swift.String = "AuthController_loginOptions"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/auth/login-options/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerLoginOptions.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerLoginOptions.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.AuthControllerLoginOptions.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.AuthControllerLoginOptions.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/login-options/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/login-options/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.LoginOptions)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.LoginOptions {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.AuthControllerLoginOptions.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.AuthControllerLoginOptions.Output.Ok.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/login-options/get(AuthController_loginOptions)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.AuthControllerLoginOptions.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.AuthControllerLoginOptions.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /api/v1/auth/login`.
    /// - Remark: Generated from `#/paths//api/v1/auth/login/post(AuthController_login)`.
    public enum AuthControllerLogin {
        public static let id: Swift.String = "AuthController_login"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/auth/login/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerLogin.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerLogin.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.AuthControllerLogin.Input.Headers
            /// - Remark: Generated from `#/paths/api/v1/auth/login/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/login/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.LoginDto)
            }
            public var body: Operations.AuthControllerLogin.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.AuthControllerLogin.Input.Headers = .init(),
                body: Operations.AuthControllerLogin.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/login/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/login/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.NativeAuthResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.NativeAuthResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.AuthControllerLogin.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.AuthControllerLogin.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Native clients receive both tokens in the body
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/login/post(AuthController_login)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.AuthControllerLogin.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.AuthControllerLogin.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/login/POST/responses/default/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/login/POST/responses/default/content/application\/json`.
                    case json(Components.Schemas.ApiError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.ApiError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.AuthControllerLogin.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.AuthControllerLogin.Output.Default.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/login/post(AuthController_login)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.AuthControllerLogin.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            public var `default`: Operations.AuthControllerLogin.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /api/v1/auth/refresh`.
    /// - Remark: Generated from `#/paths//api/v1/auth/refresh/post(AuthController_refresh)`.
    public enum AuthControllerRefresh {
        public static let id: Swift.String = "AuthController_refresh"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/auth/refresh/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerRefresh.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerRefresh.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.AuthControllerRefresh.Input.Headers
            /// - Remark: Generated from `#/paths/api/v1/auth/refresh/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/refresh/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.RefreshDto)
            }
            public var body: Operations.AuthControllerRefresh.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.AuthControllerRefresh.Input.Headers = .init(),
                body: Operations.AuthControllerRefresh.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/refresh/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/refresh/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.NativeCredentials)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.NativeCredentials {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.AuthControllerRefresh.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.AuthControllerRefresh.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Native clients receive the rotated refresh token in the body
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/refresh/post(AuthController_refresh)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.AuthControllerRefresh.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.AuthControllerRefresh.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/refresh/POST/responses/default/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/refresh/POST/responses/default/content/application\/json`.
                    case json(Components.Schemas.ApiError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.ApiError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.AuthControllerRefresh.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.AuthControllerRefresh.Output.Default.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/refresh/post(AuthController_refresh)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.AuthControllerRefresh.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            public var `default`: Operations.AuthControllerRefresh.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /api/v1/auth/logout`.
    /// - Remark: Generated from `#/paths//api/v1/auth/logout/post(AuthController_logout)`.
    public enum AuthControllerLogout {
        public static let id: Swift.String = "AuthController_logout"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/auth/logout/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerLogout.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerLogout.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.AuthControllerLogout.Input.Headers
            /// - Remark: Generated from `#/paths/api/v1/auth/logout/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/logout/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.LogoutDto)
            }
            public var body: Operations.AuthControllerLogout.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.AuthControllerLogout.Input.Headers = .init(),
                body: Operations.AuthControllerLogout.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/logout/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/logout/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIObjectContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIObjectContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.AuthControllerLogout.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.AuthControllerLogout.Output.Ok.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/logout/post(AuthController_logout)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.AuthControllerLogout.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.AuthControllerLogout.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `GET /api/v1/auth/me`.
    /// - Remark: Generated from `#/paths//api/v1/auth/me/get(AuthController_me)`.
    public enum AuthControllerMe {
        public static let id: Swift.String = "AuthController_me"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/auth/me/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerMe.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthControllerMe.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.AuthControllerMe.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.AuthControllerMe.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/me/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/me/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.AuthUser)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.AuthUser {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.AuthControllerMe.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.AuthControllerMe.Output.Ok.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/me/get(AuthController_me)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.AuthControllerMe.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.AuthControllerMe.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /api/v1/books/query`.
    /// - Remark: Generated from `#/paths//api/v1/books/query/post(BookController_globalQuery)`.
    public enum BookControllerGlobalQuery {
        public static let id: Swift.String = "BookController_globalQuery"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/books/query/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.BookControllerGlobalQuery.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.BookControllerGlobalQuery.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.BookControllerGlobalQuery.Input.Headers
            /// - Remark: Generated from `#/paths/api/v1/books/query/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/query/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.BookQuery)
            }
            public var body: Operations.BookControllerGlobalQuery.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.BookControllerGlobalQuery.Input.Headers = .init(),
                body: Operations.BookControllerGlobalQuery.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Created: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/query/POST/responses/201/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/books/query/POST/responses/201/content/application\/json`.
                    case json(Components.Schemas.BooksPage)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.BooksPage {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.BookControllerGlobalQuery.Output.Created.Body
                /// Creates a new `Created`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.BookControllerGlobalQuery.Output.Created.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/query/post(BookController_globalQuery)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.BookControllerGlobalQuery.Output.Created)
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            public var created: Operations.BookControllerGlobalQuery.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `GET /api/v1/books/files/{fileId}/progress`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/get(BookController_getFileProgress)`.
    public enum BookControllerGetFileProgress {
        public static let id: Swift.String = "BookController_getFileProgress"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/GET/path/fileId`.
                public var fileId: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - fileId:
                public init(fileId: Swift.Int) {
                    self.fileId = fileId
                }
            }
            public var path: Operations.BookControllerGetFileProgress.Input.Path
            /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.BookControllerGetFileProgress.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.BookControllerGetFileProgress.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.BookControllerGetFileProgress.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.BookControllerGetFileProgress.Input.Path,
                headers: Operations.BookControllerGetFileProgress.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.FileProgress)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.FileProgress {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.BookControllerGetFileProgress.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.BookControllerGetFileProgress.Output.Ok.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/get(BookController_getFileProgress)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.BookControllerGetFileProgress.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.BookControllerGetFileProgress.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /api/v1/books/files/{fileId}/progress`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/post(BookController_saveFileProgress)`.
    public enum BookControllerSaveFileProgress {
        public static let id: Swift.String = "BookController_saveFileProgress"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/POST/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/POST/path/fileId`.
                public var fileId: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - fileId:
                public init(fileId: Swift.Int) {
                    self.fileId = fileId
                }
            }
            public var path: Operations.BookControllerSaveFileProgress.Input.Path
            /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/progress/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.SaveProgressDto)
            }
            public var body: Operations.BookControllerSaveFileProgress.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - body:
            public init(
                path: Operations.BookControllerSaveFileProgress.Input.Path,
                body: Operations.BookControllerSaveFileProgress.Input.Body
            ) {
                self.path = path
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Created: Sendable, Hashable {
                /// Creates a new `Created`.
                public init() {}
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/post(BookController_saveFileProgress)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.BookControllerSaveFileProgress.Output.Created)
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/progress/post(BookController_saveFileProgress)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            public static var created: Self {
                .created(.init())
            }
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            public var created: Operations.BookControllerSaveFileProgress.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// - Remark: HTTP `POST /api/v1/books/files/{fileId}/sessions`.
    /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/sessions/post(ReadingSessionController_saveSession)`.
    public enum ReadingSessionControllerSaveSession {
        public static let id: Swift.String = "ReadingSessionController_saveSession"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/sessions/POST/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/sessions/POST/path/fileId`.
                public var fileId: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - fileId:
                public init(fileId: Swift.Int) {
                    self.fileId = fileId
                }
            }
            public var path: Operations.ReadingSessionControllerSaveSession.Input.Path
            /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/sessions/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/files/{fileId}/sessions/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.SaveReadingSessionDto)
            }
            public var body: Operations.ReadingSessionControllerSaveSession.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - body:
            public init(
                path: Operations.ReadingSessionControllerSaveSession.Input.Path,
                body: Operations.ReadingSessionControllerSaveSession.Input.Body
            ) {
                self.path = path
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct NoContent: Sendable, Hashable {
                /// Creates a new `NoContent`.
                public init() {}
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/sessions/post(ReadingSessionController_saveSession)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            case noContent(Operations.ReadingSessionControllerSaveSession.Output.NoContent)
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/files/{fileId}/sessions/post(ReadingSessionController_saveSession)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            public static var noContent: Self {
                .noContent(.init())
            }
            /// The associated value of the enum case if `self` is `.noContent`.
            ///
            /// - Throws: An error if `self` is not `.noContent`.
            /// - SeeAlso: `.noContent`.
            public var noContent: Operations.ReadingSessionControllerSaveSession.Output.NoContent {
                get throws {
                    switch self {
                    case let .noContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "noContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// - Remark: HTTP `GET /api/v1/books/{bookId}/bookmarks`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/get(BookmarkController_getBookmarks)`.
    public enum BookmarkControllerGetBookmarks {
        public static let id: Swift.String = "BookmarkController_getBookmarks"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/GET/path/bookId`.
                public var bookId: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - bookId:
                public init(bookId: Swift.Int) {
                    self.bookId = bookId
                }
            }
            public var path: Operations.BookmarkControllerGetBookmarks.Input.Path
            /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.BookmarkControllerGetBookmarks.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.BookmarkControllerGetBookmarks.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.BookmarkControllerGetBookmarks.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.BookmarkControllerGetBookmarks.Input.Path,
                headers: Operations.BookmarkControllerGetBookmarks.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/GET/responses/200/content/application\/json`.
                    case json([Components.Schemas.BookmarkResponseDto])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: [Components.Schemas.BookmarkResponseDto] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.BookmarkControllerGetBookmarks.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.BookmarkControllerGetBookmarks.Output.Ok.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/get(BookmarkController_getBookmarks)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.BookmarkControllerGetBookmarks.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.BookmarkControllerGetBookmarks.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /api/v1/books/{bookId}/bookmarks`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/post(BookmarkController_createBookmark)`.
    public enum BookmarkControllerCreateBookmark {
        public static let id: Swift.String = "BookmarkController_createBookmark"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/POST/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/POST/path/bookId`.
                public var bookId: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - bookId:
                public init(bookId: Swift.Int) {
                    self.bookId = bookId
                }
            }
            public var path: Operations.BookmarkControllerCreateBookmark.Input.Path
            /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.BookmarkControllerCreateBookmark.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.BookmarkControllerCreateBookmark.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.BookmarkControllerCreateBookmark.Input.Headers
            /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.CreateBookmarkDto)
            }
            public var body: Operations.BookmarkControllerCreateBookmark.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            public init(
                path: Operations.BookmarkControllerCreateBookmark.Input.Path,
                headers: Operations.BookmarkControllerCreateBookmark.Input.Headers = .init(),
                body: Operations.BookmarkControllerCreateBookmark.Input.Body
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Created: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/POST/responses/201/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/POST/responses/201/content/application\/json`.
                    case json(Components.Schemas.BookmarkResponseDto)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.BookmarkResponseDto {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.BookmarkControllerCreateBookmark.Output.Created.Body
                /// Creates a new `Created`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.BookmarkControllerCreateBookmark.Output.Created.Body) {
                    self.body = body
                }
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/post(BookmarkController_createBookmark)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.BookmarkControllerCreateBookmark.Output.Created)
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            public var created: Operations.BookmarkControllerCreateBookmark.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `DELETE /api/v1/books/{bookId}/bookmarks/{bookmarkId}`.
    /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/{bookmarkId}/delete(BookmarkController_deleteBookmark)`.
    public enum BookmarkControllerDeleteBookmark {
        public static let id: Swift.String = "BookmarkController_deleteBookmark"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/{bookmarkId}/DELETE/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/{bookmarkId}/DELETE/path/bookId`.
                public var bookId: Swift.Int
                /// - Remark: Generated from `#/paths/api/v1/books/{bookId}/bookmarks/{bookmarkId}/DELETE/path/bookmarkId`.
                public var bookmarkId: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - bookId:
                ///   - bookmarkId:
                public init(
                    bookId: Swift.Int,
                    bookmarkId: Swift.Int
                ) {
                    self.bookId = bookId
                    self.bookmarkId = bookmarkId
                }
            }
            public var path: Operations.BookmarkControllerDeleteBookmark.Input.Path
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            public init(path: Operations.BookmarkControllerDeleteBookmark.Input.Path) {
                self.path = path
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct NoContent: Sendable, Hashable {
                /// Creates a new `NoContent`.
                public init() {}
            }
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/{bookmarkId}/delete(BookmarkController_deleteBookmark)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            case noContent(Operations.BookmarkControllerDeleteBookmark.Output.NoContent)
            ///
            ///
            /// - Remark: Generated from `#/paths//api/v1/books/{bookId}/bookmarks/{bookmarkId}/delete(BookmarkController_deleteBookmark)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            public static var noContent: Self {
                .noContent(.init())
            }
            /// The associated value of the enum case if `self` is `.noContent`.
            ///
            /// - Throws: An error if `self` is not `.noContent`.
            /// - SeeAlso: `.noContent`.
            public var noContent: Operations.BookmarkControllerDeleteBookmark.Output.NoContent {
                get throws {
                    switch self {
                    case let .noContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "noContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
}
