// Generated by scripts/ipad/generate-contracts.mjs from @bookorbit/types.
// Regenerate after shared contract changes.
import Foundation

struct NativeAnnotationItem: Codable, Sendable, Equatable, Identifiable {
    var `clientId`: String? = nil
    var `kind`: String
    var `drawing`: NativeAnnotationDrawing? = nil
    var `version`: Int
    var `deletedAt`: String? = nil
    var `sourceRevision`: String? = nil
    var `pageFingerprint`: String? = nil
    var `id`: Int
    var `bookId`: Int
    var `cfi`: String? = nil
    var `jumpFileId`: Int? = nil
    var `pageno`: Int? = nil
    var `text`: String
    var `color`: String
    var `style`: String
    var `note`: String? = nil
    var `chapterTitle`: String? = nil
    var `origin`: String
    var `positionStatus`: String? = nil
    var `chapterIndex`: Int? = nil
    var `highlightedAt`: String
    var `createdAt`: String
    var `updatedAt`: String? = nil
    var `pdf`: AnnotationPdfPosition? = nil
    var `starredAt`: String? = nil
}

struct NativeAnnotationDrawing: Codable, Sendable, Equatable {
    var `format`: String
    var `strokes`: [NativeInkStroke]
    var `nativeData`: String? = nil
}

struct NativeInkStroke: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `points`: [NativeInkPoint]
    var `color`: String
    var `width`: Double
}

struct NativeInkPoint: Codable, Sendable, Equatable {
    var `x`: Double
    var `y`: Double
    var `pressure`: Double? = nil
}

struct AnnotationPdfPosition: Codable, Sendable, Equatable {
    var `page`: Int
    var `rect`: AnnotationRect
    var `rects`: [AnnotationRect]
}

struct AnnotationRect: Codable, Sendable, Equatable {
    var `x`: Double
    var `y`: Double
    var `width`: Double
    var `height`: Double
}

struct NativeAnnotationPayload: Codable, Sendable, Equatable {
    var `kind`: String? = nil
    var `drawing`: NativeAnnotationDrawing? = nil
    var `sourceRevision`: String? = nil
    var `pageFingerprint`: String? = nil
    var `cfi`: String? = nil
    var `pdf`: AnnotationPdfPosition? = nil
    var `bookFileId`: Int? = nil
    var `text`: String? = nil
    var `color`: String? = nil
    var `style`: String? = nil
    var `note`: String? = nil
    var `chapterTitle`: String? = nil
}

struct NativeAnnotationOperation: Codable, Sendable, Equatable {
    var `operationId`: String
    var `clientId`: String
    var `annotationId`: Int? = nil
    var `bookId`: Int
    var `baseVersion`: Int
    var `action`: String
    var `payload`: NativeAnnotationPayload? = nil
}

struct NativeAnnotationOperationsRequest: Codable, Sendable, Equatable {
    var `deviceId`: String
    var `operations`: [NativeAnnotationOperation]
}

struct NativeAnnotationOperationsResponse: Codable, Sendable, Equatable {
    var `results`: [NativeAnnotationOperationResult]
}

struct NativeAnnotationOperationResult: Codable, Sendable, Equatable {
    var `operationId`: String
    var `status`: String
    var `annotation`: NativeAnnotationItem? = nil
    var `draftId`: Int? = nil
    var `recoverySnapshot`: NativeAnnotationItem? = nil
    var `recoverySnapshotUnavailableReason`: String? = nil
    var `publication`: NativeAnnotationOperationResultPublication? = nil
}

struct NativeAnnotationOperationResultPublication: Codable, Sendable, Equatable {
    var `status`: String
    var `sourceRevision`: String? = nil
    var `message`: String? = nil
}

struct NativeAnnotationDelta: Codable, Sendable, Equatable {
    var `items`: [NativeAnnotationItem]
    var `nextCursor`: String
    var `hasMore`: Bool
}

struct NativeAnnotationAck: Codable, Sendable, Equatable {
    var `deviceId`: String
    var `bookId`: Int
    var `cursor`: String
}

struct NativeAnnotationDraft: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `bookId`: Int
    var `annotationId`: Int? = nil
    var `operationId`: String
    var `reason`: String
    var `payload`: NativeAnnotationOperation
    var `createdAt`: String
    var `snapshot`: NativeAnnotationItem? = nil
    var `snapshotUnavailableReason`: String? = nil
}

struct NativeAnnotationHubItem: Codable, Sendable, Equatable, Identifiable {
    var `bookTitle`: String? = nil
    var `author`: String? = nil
    var `fileFormat`: String? = nil
    var `groupKey`: String
    var `clientId`: String? = nil
    var `kind`: String
    var `drawing`: NativeAnnotationDrawing? = nil
    var `version`: Int
    var `deletedAt`: String? = nil
    var `sourceRevision`: String? = nil
    var `pageFingerprint`: String? = nil
    var `id`: Int
    var `bookId`: Int
    var `cfi`: String? = nil
    var `jumpFileId`: Int? = nil
    var `pageno`: Int? = nil
    var `text`: String
    var `color`: String
    var `style`: String
    var `note`: String? = nil
    var `chapterTitle`: String? = nil
    var `origin`: String
    var `positionStatus`: String? = nil
    var `chapterIndex`: Int? = nil
    var `highlightedAt`: String
    var `createdAt`: String
    var `updatedAt`: String? = nil
    var `pdf`: AnnotationPdfPosition? = nil
    var `starredAt`: String? = nil
}

struct NativeAnnotationHubResponse: Codable, Sendable, Equatable {
    var `items`: [NativeAnnotationHubItem]
    var `nextCursor`: Int? = nil
}

struct NativeAnnotationHubDevice: Codable, Sendable, Equatable {
    var `deviceId`: String
    var `bookId`: Int
    var `cursor`: Int
    var `updatedAt`: String
}

struct NativeAnnotationHubDeviceResponse: Codable, Sendable, Equatable {
    var `items`: [NativeAnnotationHubDevice]
    var `nextCursor`: String? = nil
}

struct NativeAnnotationDraftResponse: Codable, Sendable, Equatable {
    var `items`: [NativeAnnotationDraft]
    var `nextCursor`: Int? = nil
}

struct NativePdfPageSource: Codable, Sendable, Equatable {
    var `sourceRevision`: String
    var `pageFingerprint`: String
    var `width`: Double
    var `height`: Double
    var `page`: Int
    var `canEditPdfInk`: Bool
    var `matchedSourceRevision`: String?
}

struct NativePdfPageSourceBatch: Codable, Sendable, Equatable {
    var `sourceRevision`: String
    var `pages`: [NativePdfPageSource]
    var `nextPage`: Int?
}

struct DictionaryResult: Codable, Sendable, Equatable {
    var `word`: String
    var `phonetic`: String?
    var `audioUrl`: String?
    var `entries`: [DictionaryEntry]
    var `provider`: String
}

struct DictionaryEntry: Codable, Sendable, Equatable {
    var `partOfSpeech`: String
    var `definitions`: [DictionaryDefinition]
    var `sourceWord`: String
}

struct DictionaryDefinition: Codable, Sendable, Equatable {
    var `definition`: String
    var `example`: String?
}

struct TranslationResult: Codable, Sendable, Equatable {
    var `translatedText`: String
    var `detectedSourceLang`: String
    var `provider`: String
}

struct SupportedLanguage: Codable, Sendable, Equatable {
    var `code`: String
    var `name`: String
}

struct CreateAnnotationPayload: Encodable, Sendable, Equatable {
    var `cfi`: String?
    var `bookFileId`: Int?
    var `text`: String
    var `color`: String?
    var `style`: String?
    var `note`: String?
    var `chapterTitle`: String?
}

struct AnnotationListResponse: Codable, Sendable, Equatable {
    var `items`: [AnnotationItem]
    var `total`: Int
    var `page`: Int
    var `pageSize`: Int
}

struct AnnotationItem: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `bookId`: Int
    var `cfi`: String?
    var `jumpFileId`: Int?
    var `text`: String
    var `color`: String
    var `style`: String
    var `note`: String?
    var `chapterTitle`: String?
    var `positionStatus`: String?
}

struct AudiobookManifest: Codable, Sendable, Equatable {
    var `schema`: String
    var `schemaVersion`: Int
    var `revision`: String
    var `book`: AudiobookManifestBook
    var `assets`: [AudiobookManifestAsset]
    var `chapters`: [AudiobookManifestChapter]
    var `totalDurationMs`: Int
}

struct AudiobookManifestBook: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `title`: String
    var `authors`: [String]
    var `narrators`: [String]
    var `hasCover`: Bool
}

struct AudiobookManifestAsset: Codable, Sendable, Equatable {
    var `assetId`: String
    var `fileId`: Int
    var `sequence`: Int
    var `format`: String
    var `durationMs`: Int?
    var `sizeBytes`: Double?
    var `etag`: String
}

struct AudiobookManifestChapter: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `title`: String
    var `assetId`: String
    var `sequence`: Int
    var `startMs`: Int
    var `endMs`: Int
    var `assetOffsetMs`: Int
}

struct AudiobookPlaybackState: Codable, Sendable, Equatable {
    var `assetId`: String
    var `positionMs`: Int
    var `percentage`: Double
    var `completed`: Bool
    var `capturedAt`: String
    var `revision`: Int
    var `manifestRevision`: String
}

struct AudiobookBookmark: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `bookId`: Int
    var `positionMs`: Int
    var `chapterId`: String?
    var `title`: String
    var `note`: String?
    var `createdAt`: String
    var `updatedAt`: String
}

struct AudiobookBookmarksPage: Codable, Sendable, Equatable {
    var `items`: [AudiobookBookmark]
    var `nextCursor`: String?
}

struct CreateAudiobookBookmark: Codable, Sendable, Equatable {
    var `clientId`: String
    var `positionMs`: Int
    var `chapterId`: String?
    var `title`: String
    var `note`: String?
}

struct UpdateAudiobookBookmark: Encodable, Sendable, Equatable {
    var `title`: String?
    var `note`: FieldUpdate<String>?
}

struct PutAudiobookPlaybackState: Encodable, Sendable, Equatable {
    var `assetId`: String
    var `positionMs`: Int
    var `capturedAt`: String
    var `operationId`: String
    var `baseRevision`: Int
    var `manifestRevision`: String
}

struct DeleteAudiobookPlaybackStateQuery: Encodable, Sendable, Equatable {
    var `baseRevision`: Int?
    var `manifestRevision`: String?
}

struct NativeAuthResponse: Codable, Sendable, Equatable {
    var `user`: AuthUser
    var `accessToken`: String
    var `accessTokenExpiresAt`: String
    var `refreshToken`: String
    var `refreshTokenExpiresAt`: String
    var `sessionId`: Int
}

struct AuthUser: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `username`: String
    var `name`: String
    var `active`: Bool
    var `isSuperuser`: Bool
    var `isDefaultPassword`: Bool
    var `permissions`: [String]
    var `settings`: UserSettings
}

struct UserSettings: Codable, Sendable, Equatable {
    var `dashboardConfig`: DashboardConfig?
    var `dashboardShelfConfig`: DashboardShelfConfig?
    var `syncReaderPreferences`: Bool?
    var `timezone`: String?
    var `seriesCollapsePreferences`: SeriesCollapsePreferences?
}

struct DashboardConfig: Codable, Sendable, Equatable {
    var `readingGoal`: Double?
    var `widgets`: [WidgetConfig]?
    var `libraryIds`: [Int]?
}

struct WidgetConfig: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `type`: String
    var `enabled`: Bool
    var `order`: Double
}

struct DashboardShelfConfig: Codable, Sendable, Equatable {
    var `syncAcrossSessions`: Bool?
    var `scrollers`: [ScrollerConfig]?
    var `shelfLayout`: String?
}

struct ScrollerConfig: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `type`: String
    var `label`: String
    var `enabled`: Bool
    var `order`: Double
    var `limit`: Double
    var `rows`: Double
    var `smartScopeId`: Int?
}

struct SeriesCollapsePreferences: Codable, Sendable, Equatable {
    var `global`: Bool
    var `libraries`: [String: Bool]
    var `collections`: [String: Bool]
    var `smartScopes`: [String: Bool]?
    var `authorPages`: Bool?
}

struct NativeCredentials: Codable, Sendable, Equatable {
    var `accessToken`: String
    var `accessTokenExpiresAt`: String
    var `refreshToken`: String
    var `refreshTokenExpiresAt`: String
    var `sessionId`: Int
}

struct LoginRequest: Codable, Sendable, Equatable {
    var `username`: String
    var `password`: String
    var `clientKind`: String?
    var `deviceLabel`: String?
}

struct RefreshRequest: Codable, Sendable, Equatable {
    var `refreshToken`: String?
}

struct ChangePasswordRequest: Codable, Sendable, Equatable {
    var `currentPassword`: String
    var `newPassword`: String
}

struct ForgotPasswordRequest: Codable, Sendable, Equatable {
    var `email`: String
}

struct ResetPasswordRequest: Codable, Sendable, Equatable {
    var `token`: String
    var `newPassword`: String
}

struct OidcStateResponse: Codable, Sendable, Equatable {
    var `state`: String
    var `authorizationEndpoint`: String
}

struct OidcCallbackRequest: Codable, Sendable, Equatable {
    var `code`: String
    var `codeVerifier`: String
    var `redirectUri`: String
    var `nonce`: String
    var `state`: String
    var `clientKind`: String?
    var `deviceLabel`: String?
}

struct LoginOptionsResponse: Codable, Sendable, Equatable {
    var `passwordLoginEnabled`: Bool
    var `allowRegistration`: Bool
    var `oidcProviders`: [OidcProviderPublic]
}

struct OidcProviderPublic: Codable, Sendable, Equatable {
    var `slug`: String
    var `displayName`: String
    var `enabled`: Bool
    var `iconUrl`: String?
    var `clientId`: String
    var `scopes`: String
}

struct Library: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `type`: String
    var `accessLevel`: String?
    var `name`: String
    var `bookCount`: Int?
}

struct BooksPage: Codable, Sendable, Equatable {
    var `items`: [BookCard]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct BookCard: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `title`: String?
    var `authors`: [String]
    var `files`: [BookFileRef]
    var `hasCover`: Bool
    var `coverVersion`: String
    var `readingProgress`: Double?
    var `seriesName`: String?
    var `seriesId`: Int?
    var `seriesIndex`: String?
    var `publishedDate`: String?
    var `publishedYear`: Int?
    var `language`: String?
    var `rating`: Double?
    var `metadataScore`: Double?
    var `genres`: [String]
    var `tags`: [String]
    var `subtitle`: String?
    var `publisher`: String?
    var `pageCount`: Int?
    var `isbn13`: String?
    var `narrators`: [String]
    var `readStatus`: UserBookStatus?
    var `updatedAt`: String?
    var `addedAt`: String
    var `lockedFields`: [String]
    var `customMetadata`: [CustomMetadataBookValue]
    var `collapsedSeries`: CollapsedSeriesInfo?
}

struct BookFileRef: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `format`: String?
    var `role`: String
    var `sizeBytes`: Double?
    var `mediaOverlay`: EpubMediaOverlayCapability?
}

struct EpubMediaOverlayCapability: Codable, Sendable, Equatable {
    var `available`: Bool
    var `durationSeconds`: Double?
}

struct UserBookStatus: Codable, Sendable, Equatable {
    var `status`: String
    var `source`: String
    var `startedAt`: String?
    var `finishedAt`: String?
    var `updatedAt`: String
}

struct CustomMetadataBookValue: Codable, Sendable, Equatable {
    var `fieldId`: Int
    var `key`: String
    var `label`: String
    var `type`: String
    var `displayOrder`: Int
    var `value`: CustomMetadataPrimitiveValue
}

enum CustomMetadataPrimitiveValue: Codable, Sendable, Equatable {
    case string(String), number(Double), boolean(Bool), null

    init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null }
        else if let value = try? container.decode(Bool.self) { self = .boolean(value) }
        else if let value = try? container.decode(Double.self) { self = .number(value) }
        else { self = .string(try container.decode(String.self)) }
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .boolean(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}

struct CollapsedSeriesInfo: Codable, Sendable, Equatable {
    var `bookCount`: Int
    var `readCount`: Int
    var `coverBookIds`: [Int]
    var `coverUpdatedAtByBookId`: [String: String?]?
    var `seriesLatestAddedAt`: String?
    var `firstVolumeBookId`: Int?
    var `latestVolumeBookId`: Int?
    var `firstUnreadBookId`: Int?
}

struct CustomMetadataFieldSummary: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `label`: String
    var `type`: String
    var `displayOrder`: Int
    var `archivedAt`: String?
    var `enabledLibraryIds`: [Int]
}

struct CatalogSearchResult: Codable, Sendable, Equatable, Identifiable {
    var `name`: String
    var `id`: Int?
}

struct BookDetail: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `status`: String
    var `libraryId`: Int
    var `libraryName`: String
    var `addedAt`: String
    var `title`: String?
    var `subtitle`: String?
    var `description`: String?
    var `publisher`: String?
    var `publishedDate`: String?
    var `publishedYear`: Int?
    var `language`: String?
    var `pageCount`: Int?
    var `isbn10`: String?
    var `isbn13`: String?
    var `authors`: [BookDetailAuthorsItem]
    var `genres`: [String]
    var `tags`: [String]
    var `customMetadata`: [CustomMetadataBookValue]
    var `seriesName`: String?
    var `seriesId`: Int?
    var `seriesIndex`: String?
    var `seriesMemberships`: [BookSeriesMembership]?
    var `rating`: Double?
    var `readStatus`: UserBookStatus?
    var `personalNote`: String?
    var `personalNoteUpdatedAt`: String?
    var `communityRatings`: [BookCommunityRating]
    var `providerIds`: BookDetailProviderIds
    var `hardcoverEditionId`: String?
    var `audioMetadata`: AudioMetadata?
    var `readAloudSync`: ReadAloudProgressSync
    var `comicMetadata`: ComicMetadataFields?
    var `files`: [BookDetailFile]
    var `fileWriteStatus`: BookFileWriteStatus?
    var `lastWrittenAt`: String?
    var `lockedFields`: [String]
    var `coverMedia`: [CoverMedium]
    var `covers`: BookDetailCovers
    var `coverVersion`: String
}

struct BookDetailAuthorsItem: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `sortName`: String?
}

struct BookSeriesMembership: Codable, Sendable, Equatable {
    var `seriesId`: Int
    var `seriesName`: String
    var `seriesIndex`: String?
    var `displayOrder`: Int
    var `expectedBookCount`: Int?
}

struct BookCommunityRating: Codable, Sendable, Equatable {
    var `provider`: String
    var `rating`: Double
    var `ratingCount`: Int?
    var `updatedAt`: String?
}

struct BookDetailProviderIds: Codable, Sendable, Equatable {
    var `kobo`: String?
    var `google`: String?
    var `goodreads`: String?
    var `amazon`: String?
    var `hardcover`: String?
    var `openLibrary`: String?
    var `itunes`: String?
    var `audible`: String?
    var `audnexus`: String?
    var `librofm`: String?
    var `comicvine`: String?
    var `ranobedb`: String?
    var `lubimyczytac`: String?
    var `aladin`: String?
}

struct AudioMetadata: Codable, Sendable, Equatable {
    var `narrators`: [NarratorRef]
    var `durationSeconds`: Int?
    var `abridged`: Bool
    var `chapters`: [AudiobookChapter]?
}

struct NarratorRef: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `sortName`: String?
    var `displayOrder`: Int
}

struct AudiobookChapter: Codable, Sendable, Equatable {
    var `title`: String
    var `startMs`: Int
}

struct ReadAloudProgressSync: Codable, Sendable, Equatable {
    var `mode`: String
    var `state`: String
    var `unavailableReason`: String?
    var `overlayFileId`: Int?
    var `audioDurationSeconds`: Double?
    var `overlayDurationSeconds`: Double?
    var `durationDifferenceSeconds`: Double?
    var `durationDifferenceRatio`: Double?
    var `koreaderDownloadAvailable`: Bool
}

struct ComicMetadataFields: Codable, Sendable, Equatable {
    var `issueNumber`: String?
    var `volumeName`: String?
    var `pencillers`: [String]?
    var `inkers`: [String]?
    var `colorists`: [String]?
    var `letterers`: [String]?
    var `coverArtists`: [String]?
    var `characters`: [String]?
    var `teams`: [String]?
    var `locations`: [String]?
    var `storyArcs`: [String]?
}

struct BookDetailFile: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `format`: String?
    var `role`: String
    var `filename`: String?
    var `sizeBytes`: Double?
    var `durationSeconds`: Int?
    var `mediaOverlay`: EpubMediaOverlayCapability?
    var `absolutePath`: String
}

struct BookFileWriteStatus: Codable, Sendable, Equatable {
    var `enabled`: Bool
    var `reason`: String?
    var `writableFormats`: [String]
    var `writableFields`: [String]
    var `targets`: [BookFileWriteTargetStatus]?
}

struct BookFileWriteTargetStatus: Codable, Sendable, Equatable {
    var `fileId`: Int
    var `format`: String?
    var `writable`: Bool
    var `reason`: String?
    var `writableFields`: [String]
}

struct BookDetailCovers: Codable, Sendable, Equatable {
    var `ebook`: BookCoverSlot?
    var `audio`: BookCoverSlot?
}

struct BookCoverSlot: Codable, Sendable, Equatable {
    var `source`: String
    var `updatedAt`: String
    var `width`: Int?
    var `height`: Int?
}

struct UpdateBookReadAloudSyncPayload: Encodable, Sendable, Equatable {
    var `mode`: String
}

struct BookWriteAndRenameResult: Codable, Sendable, Equatable {
    var `write`: WriteResult
    var `rename`: FileRenameResult
    var `libraryAutoWriteEnabled`: Bool
    var `libraryAutoRenameEnabled`: Bool
}

struct WriteResult: Codable, Sendable, Equatable {
    var `status`: String
    var `fieldsWritten`: [String]
    var `durationMs`: Int
    var `reason`: String?
    var `fileCounts`: WriteResultFileCounts?
}

struct WriteResultFileCounts: Codable, Sendable, Equatable {
    var `processed`: Int
    var `succeeded`: Int
    var `failed`: Int
    var `skipped`: Int
}

struct FileRenameResult: Codable, Sendable, Equatable {
    var `status`: String
    var `reason`: String?
    var `oldPath`: String?
    var `newPath`: String?
    var `durationMs`: Int
}

struct BookContinuationQuery: Codable, Sendable, Equatable {
    var `direction`: String
    var `sourceFileId`: Int
    var `textCfi`: String?
    var `audioRevision`: Int?
}

struct BookContinuationResponse: Codable, Sendable, Equatable {
    var `sourceFileId`: Int
    var `sourceTextCfi`: String?
    var `sourceAudioRevision`: Int?
    var `sourcePositionMs`: Int?
    var `accuracy`: String?
    var `state`: String
    var `reason`: String?
    var `overlayFileId`: Int?
    var `targets`: [BookContinuationTarget]
}

struct BookContinuationTarget: Codable, Sendable, Equatable {
    var `fileId`: Int
    var `format`: String
    var `filename`: String
    var `cfi`: String?
    var `assetId`: String?
    var `positionMs`: Int?
    var `sequence`: Int?
}

struct BookQuery: Codable, Sendable, Equatable {
    var `filter`: GroupRule?
    var `sort`: [SortSpec]
    var `pagination`: BookQueryPagination
    var `q`: String?
    var `collapseSeries`: Bool?
    var `randomSeed`: Int?
}

struct GroupRule: Codable, Sendable, Equatable {
    var `type`: String
    var `join`: String
    var `rules`: [FilterNode]
}

indirect enum FilterNode: Codable, Sendable, Equatable {
    case rule(Rule)
    case group(GroupRule)

    private enum CodingKeys: String, CodingKey { case type }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        switch try container.decode(String.self, forKey: .type) {
        case "rule": self = .rule(try Rule(from: decoder))
        case "group": self = .group(try GroupRule(from: decoder))
        default: throw DecodingError.dataCorruptedError(forKey: .type, in: container, debugDescription: "Invalid filter node")
        }
    }

    func encode(to encoder: any Encoder) throws {
        switch self {
        case .rule(let value): try value.encode(to: encoder)
        case .group(let value): try value.encode(to: encoder)
        }
    }
}

struct Rule: Codable, Sendable, Equatable {
    var `type`: String
    var `field`: String
    var `operator`: String
    var `value`: RuleValue?
    var `valueTo`: RuleValueTo?
    var `provider`: String?
}

enum RuleValue: Codable, Sendable, Equatable {
    case string(String)
    case number(Double)
    case numbers([Double])
    case strings([String])

    init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) { self = .string(value); return }
        if let value = try? container.decode(Double.self) { self = .number(value); return }
        if let value = try? container.decode([Double].self) { self = .numbers(value); return }
        if let value = try? container.decode([String].self) { self = .strings(value); return }
        throw DecodingError.typeMismatch(Self.self, .init(codingPath: decoder.codingPath, debugDescription: "Invalid filter value"))
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .numbers(let value): try container.encode(value)
        case .strings(let value): try container.encode(value)
        }
    }
}

enum RuleValueTo: Codable, Sendable, Equatable {
    case string(String)
    case number(Double)

    init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) { self = .string(value); return }
        if let value = try? container.decode(Double.self) { self = .number(value); return }
        throw DecodingError.typeMismatch(Self.self, .init(codingPath: decoder.codingPath, debugDescription: "Invalid filter value"))
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        }
    }
}

struct SortSpec: Codable, Sendable, Equatable {
    var `field`: String
    var `dir`: String
}

struct BookQueryPagination: Codable, Sendable, Equatable {
    var `page`: Int
    var `size`: Int
}

struct CollectionsPage: Codable, Sendable, Equatable {
    var `items`: [BookCollection]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct BookCollection: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `userId`: Int
    var `mediaType`: String
    var `name`: String
    var `icon`: String?
    var `isPublic`: Bool
    var `isOwner`: Bool
    var `bookCount`: Int
    var `memberCount`: Int?
}

struct CollectionPageQuery: Codable, Sendable, Equatable {
    var `page`: Int?
    var `size`: Int?
    var `q`: String?
    var `mediaType`: String?
    var `owned`: Bool?
    var `bookId`: Int?
}

struct CreateCollectionPayload: Codable, Sendable, Equatable {
    var `name`: String
    var `icon`: String
    var `description`: String?
    var `mediaType`: String?
    var `isPublic`: Bool?
    var `syncToKobo`: Bool?
}

struct UpdateCollectionPayload: Codable, Sendable, Equatable {
    var `name`: String?
    var `description`: String?
    var `icon`: String?
    var `isPublic`: Bool?
    var `syncToKobo`: Bool?
}

struct BookIdsSelection: Codable, Sendable, Equatable {
    var `bookIds`: [Int]
}

struct BookMoveExplicitPreviewRequest: Codable, Sendable, Equatable {
    var `selection`: BookIdsSelection
    var `targetLibraryId`: Int
    var `targetFolderId`: Int
}

struct BookMoveExplicitExecuteRequest: Codable, Sendable, Equatable {
    var `selection`: BookIdsSelection
    var `targetLibraryId`: Int
    var `targetFolderId`: Int
    var `collisionPolicy`: String
    var `overrides`: [BookMoveCollisionOverride]?
}

struct BookMoveCollisionOverride: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `policy`: String
}

struct BookMoveDestinationQuery: Codable, Sendable, Equatable {
    var `sourceLibraryId`: Int
    var `page`: Int?
    var `size`: Int?
    var `q`: String?
}

struct BookMoveFolderQuery: Codable, Sendable, Equatable {
    var `page`: Int?
    var `size`: Int?
    var `q`: String?
}

struct BookMoveDestinationsPage: Codable, Sendable, Equatable {
    var `items`: [BookMoveDestination]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct BookMoveDestination: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `organizationMode`: String
}

struct BookMoveFoldersPage: Codable, Sendable, Equatable {
    var `libraryId`: Int
    var `items`: [BookMoveFolder]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct BookMoveFolder: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `path`: String
}

struct BookMovePreviewResult: Codable, Sendable, Equatable {
    var `targetLibraryId`: Int
    var `targetFolderId`: Int
    var `targetOrganizationMode`: String
    var `totalSelected`: Int
    var `readyCount`: Int
    var `ready`: [BookMovePreviewReadyItem]
    var `alreadyInTargetCount`: Int
    var `collisionCount`: Int
    var `collisions`: [BookMovePreviewCollisionItem]
    var `collisionsTruncated`: Bool
    var `ineligibleCount`: Int
    var `ineligible`: [BookMovePreviewIneligibleItem]
    var `ineligibleTruncated`: Bool
    var `warnings`: BookMoveWarnings
    var `requiresReview`: Bool
}

struct BookMovePreviewReadyItem: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `title`: String
    var `currentPath`: String
    var `targetPath`: String
    var `layoutChange`: String?
}

struct BookMovePreviewCollisionItem: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `title`: String
    var `kind`: String
    var `currentPath`: String
    var `targetPath`: String
    var `existingBookId`: Int?
    var `suggestedPolicy`: String
    var `keepBothPath`: String
}

struct BookMovePreviewIneligibleItem: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `title`: String
    var `reason`: String
    var `detail`: String?
}

struct BookMoveWarnings: Codable, Sendable, Equatable {
    var `accessLosers`: [BookMoveAccessLoser]
    var `koboImpact`: [BookMoveKoboImpact]
    var `layout`: BookMoveLayoutSummary?
    var `formatMismatches`: [BookMoveFormatMismatch]
    var `crossDevice`: Bool
}

struct BookMoveAccessLoser: Codable, Sendable, Equatable {
    var `userId`: Int
    var `username`: String
    var `bookCount`: Int
}

struct BookMoveKoboImpact: Codable, Sendable, Equatable {
    var `userId`: Int
    var `username`: String
    var `deviceCount`: Int
    var `bookCount`: Int
}

struct BookMoveLayoutSummary: Codable, Sendable, Equatable {
    var `change`: String
    var `bookCount`: Int
}

struct BookMoveFormatMismatch: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `title`: String
    var `format`: String
}

struct BookMoveBookProgress: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `status`: String
    var `reason`: String?
}

struct BookMoveCompletionEvent: Codable, Sendable, Equatable {
    var `done`: Bool
    var `processed`: Int
    var `succeeded`: Int
    var `merged`: Int
    var `failed`: Int
    var `skipped`: Int
    var `cancelled`: Bool
}

struct BookMetadataUpdatePayload: Encodable, Sendable, Equatable {
    var `publisher`: FieldUpdate<String>?
    var `language`: FieldUpdate<String>?
    var `pageCount`: FieldUpdate<Int>?
    var `genres`: [String]?
    var `tags`: [String]?
    var `description`: FieldUpdate<String>?
    var `title`: FieldUpdate<String>?
    var `subtitle`: FieldUpdate<String>?
    var `publishedYear`: FieldUpdate<Int>?
    var `seriesName`: FieldUpdate<String>?
    var `seriesIndex`: FieldUpdate<String>?
    var `isbn13`: FieldUpdate<String>?
    var `isbn10`: FieldUpdate<String>?
    var `rating`: FieldUpdate<Double>?
    var `publishedDate`: FieldUpdate<String>?
    var `googleBooksId`: FieldUpdate<String>?
    var `goodreadsId`: FieldUpdate<String>?
    var `amazonId`: FieldUpdate<String>?
    var `hardcoverId`: FieldUpdate<String>?
    var `hardcoverEditionId`: FieldUpdate<String>?
    var `openLibraryId`: FieldUpdate<String>?
    var `itunesId`: FieldUpdate<String>?
    var `audibleId`: FieldUpdate<String>?
    var `librofmId`: FieldUpdate<String>?
    var `koboId`: FieldUpdate<String>?
    var `comicvineId`: FieldUpdate<String>?
    var `ranobedbId`: FieldUpdate<String>?
    var `lubimyczytacId`: FieldUpdate<String>?
    var `aladinId`: FieldUpdate<String>?
    var `authors`: [String]?
    var `customMetadata`: [CustomMetadataBookValueInput]?
    var `seriesMemberships`: FieldUpdate<[BookSeriesMembershipUpdatePayload]>?
    var `communityRatings`: FieldUpdate<[BookCommunityRatingUpdatePayload]>?
    var `audioMetadata`: AudioMetadataUpdatePayload?
    var `comicMetadata`: ComicMetadataUpdatePayload?
}

struct CustomMetadataBookValueInput: Codable, Sendable, Equatable {
    var `fieldId`: Int
    var `value`: CustomMetadataPrimitiveValue
}

struct BookSeriesMembershipUpdatePayload: Encodable, Sendable, Equatable {
    var `seriesName`: String
    var `seriesIndex`: FieldUpdate<String>?
    var `expectedBookCount`: FieldUpdate<Int>?
}

struct BookCommunityRatingUpdatePayload: Codable, Sendable, Equatable {
    var `provider`: String
    var `rating`: Double
    var `ratingCount`: Int?
}

struct AudioMetadataUpdatePayload: Encodable, Sendable, Equatable {
    var `narrators`: [String]?
    var `durationSeconds`: FieldUpdate<Int>?
    var `abridged`: FieldUpdate<Bool>?
    var `chapters`: FieldUpdate<[AudiobookChapterUpdatePayload]>?
}

struct AudiobookChapterUpdatePayload: Codable, Sendable, Equatable {
    var `title`: String
    var `startMs`: Int
    var `durationMs`: Int?
}

struct ComicMetadataUpdatePayload: Encodable, Sendable, Equatable {
    var `pencillers`: [String]?
    var `inkers`: [String]?
    var `colorists`: [String]?
    var `letterers`: [String]?
    var `coverArtists`: [String]?
    var `characters`: [String]?
    var `teams`: [String]?
    var `locations`: [String]?
    var `storyArcs`: [String]?
    var `issueNumber`: FieldUpdate<String>?
    var `volumeName`: FieldUpdate<String>?
}

struct BookMetadataAndLocksUpdatePayload: Encodable, Sendable, Equatable {
    var `metadata`: BookMetadataUpdatePayload?
    var `lockedFields`: [String]
}

struct BookAddedAtUpdatePayload: Encodable, Sendable, Equatable {
    var `addedAt`: String
}

struct FileReadingProgress: Codable, Sendable, Equatable {
    var `cfi`: String?
    var `pageNumber`: Double?
    var `percentage`: Double
    var `positionSeconds`: Double?
    var `mediaOverlayFragment`: String?
    var `mediaOverlaySectionIndex`: Int?
    var `koboLocationSource`: String?
    var `koboLocationType`: String?
    var `koboLocationValue`: String?
    var `koboContentSourceProgressPercent`: Double?
    var `koreaderProgress`: String?
    var `narrationPercentage`: Double?
    var `narrationUpdatedAt`: String?
    var `textUpdatedAt`: String?
    var `textVersion`: String?
    var `narrationVersion`: String?
}

struct SaveFileProgressPayload: Encodable, Sendable, Equatable {
    var `cfi`: String?
    var `pageNumber`: Double?
    var `positionSeconds`: Double?
    var `mediaOverlayFragment`: String?
    var `mediaOverlaySectionIndex`: Int?
    var `koboLocationSource`: String?
    var `koboLocationType`: String?
    var `koboLocationValue`: String?
    var `koboContentSourceProgressPercent`: Double?
    var `koreaderProgress`: String?
    var `percentage`: Double
    var `source`: String?
    var `baseVersion`: String?
}

struct ClearFileProgressQuery: Encodable, Sendable, Equatable {
    var `textVersion`: String?
    var `narrationVersion`: String?
}

struct EpubBookInfo: Codable, Sendable, Equatable {
    var `containerPath`: String
    var `rootPath`: String
    var `spine`: [EpubSpineItem]
    var `manifest`: [EpubManifestItem]
    var `optionalFiles`: [String]?
    var `toc`: EpubTocItem?
}

struct EpubSpineItem: Codable, Sendable, Equatable {
    var `idref`: String
    var `href`: String
    var `mediaType`: String
    var `linear`: Bool
}

struct EpubManifestItem: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `href`: String
    var `mediaType`: String
    var `properties`: [String]?
    var `mediaOverlay`: String?
    var `size`: Int
}

struct EpubTocItem: Codable, Sendable, Equatable {
    var `label`: String
    var `href`: String?
    var `children`: [EpubTocItem]?
}

struct EpubMediaOverlayClipsPage: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `fileId`: Int?
    var `sectionIndex`: Int
    var `nextSectionIndex`: Int?
    var `previousSectionIndex`: Int?
    var `totalClips`: Int
    var `items`: [EpubMediaOverlayClip]
    var `nextCursor`: Int?
}

struct EpubMediaOverlayClip: Codable, Sendable, Equatable {
    var `sectionClipIndex`: Int
    var `startSeconds`: Double?
    var `audioSizeBytes`: Double
    var `index`: Int
    var `sectionIndex`: Int
    var `smilHref`: String
    var `textHref`: String
    var `textFragment`: String?
    var `audioHref`: String
    var `audioMimeType`: String
    var `clipBeginSeconds`: Double
    var `clipEndSeconds`: Double?
    var `durationSeconds`: Double?
    var `label`: String?
}

struct ComicPageCountResponse: Codable, Sendable, Equatable {
    var `pageCount`: Int
}

struct AuthorsPage: Codable, Sendable, Equatable {
    var `items`: [AuthorSummary]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct AuthorSummary: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `sortName`: String?
    var `description`: String?
    var `imageUrl`: String?
    var `bookCount`: Int
    var `lastAddedAt`: String?
    var `coverBookId`: Int?
}

struct AuthorDetail: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `sortName`: String?
    var `description`: String?
    var `imageUrl`: String?
    var `bookCount`: Int
    var `lastAddedAt`: String?
    var `coverBookId`: Int?
    var `birthDate`: String?
    var `birthYear`: Int?
    var `deathDate`: String?
    var `deathYear`: Int?
    var `website`: String?
    var `genres`: [String]
    var `influences`: [String]
    var `metadataProvider`: String?
    var `metadataProviderId`: String?
}

struct AuthorBooksPage: Codable, Sendable, Equatable {
    var `items`: [BookCard]
    var `total`: Int
    var `page`: Int
    var `size`: Int
    var `bookTotal`: Int
}

struct SeriesPage: Codable, Sendable, Equatable {
    var `items`: [SeriesSummary]
    var `total`: Int
    var `page`: Int
    var `size`: Int
    var `facets`: SeriesFacets
}

struct SeriesSummary: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `bookCount`: Int
    var `readCount`: Int
    var `authors`: [String]
    var `coverBookIds`: [Int]
    var `lastAddedAt`: String?
    var `readingCount`: Int
    var `libraryNames`: [String]
    var `expectedBookCount`: Int?
    var `volumes`: [SeriesVolumeSlot]
    var `volumesTruncated`: Bool
    var `gaps`: [Int]
    var `gapCount`: Int
    var `nextBookId`: Int?
    var `nextIndex`: String?
    var `nextTitle`: String?
}

struct SeriesVolumeSlot: Codable, Sendable, Equatable {
    var `index`: Int?
    var `bookId`: Int?
    var `title`: String?
    var `status`: String
}

struct SeriesFacets: Codable, Sendable, Equatable {
    var `all`: Int
    var `notStarted`: Int
    var `inProgress`: Int
    var `complete`: Int
    var `hasGaps`: Int
}

struct SeriesBooksPage: Codable, Sendable, Equatable {
    var `items`: [BookCard]
    var `total`: Int
    var `page`: Int
    var `size`: Int
    var `seriesInfo`: SeriesDetail
}

struct SeriesDetail: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `bookCount`: Int
    var `readCount`: Int
    var `authors`: [String]
    var `possibleGaps`: [Int]
    var `expectedBookCount`: Int?
}

struct SeriesNextBookResponse: Codable, Sendable, Equatable {
    var `next`: SeriesNextBook?
}

struct SeriesNextBook: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `fileId`: Int
    var `format`: String
    var `title`: String?
    var `seriesIndex`: String?
}

struct UpdateSeriesCollapsePreferencesPayload: Encodable, Sendable, Equatable {
    var `global`: Bool?
    var `authorPages`: Bool?
    var `libraries`: [String: Bool?]?
    var `collections`: [String: Bool?]?
    var `smartScopes`: [String: Bool?]?
}

struct DashboardScrollerBatchRequest: Codable, Sendable, Equatable {
    var `items`: [DashboardScrollerBatchItem]
}

struct DashboardScrollerBatchItem: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `type`: String
    var `limit`: Double
    var `smartScopeId`: Int?
}

struct DashboardScrollerBatchResponse: Codable, Sendable, Equatable {
    var `items`: [DashboardScrollerBatchResult]
}

struct DashboardScrollerBatchResult: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `books`: [BookCard]
    var `failed`: Bool
}

struct SmartScopesPage: Codable, Sendable, Equatable {
    var `items`: [BookSmartScope]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct BookSmartScope: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `userId`: Int
    var `mediaType`: String
    var `name`: String
    var `icon`: String?
    var `filter`: GroupRule?
    var `defaultSort`: [SortSpec]
    var `isPublic`: Bool
    var `syncToKobo`: Bool
    var `koboSyncEnabled`: Bool
    var `isOwner`: Bool
}

struct SmartScopePageQuery: Codable, Sendable, Equatable {
    var `page`: Int?
    var `size`: Int?
    var `q`: String?
    var `mediaType`: String?
    var `owned`: Bool?
}

struct CreateSmartScopePayload: Codable, Sendable, Equatable {
    var `name`: String
    var `icon`: String
    var `mediaType`: String?
    var `libraryId`: Int?
    var `filter`: GroupRule?
    var `defaultSort`: [SortSpec]
    var `isPublic`: Bool?
    var `syncToKobo`: Bool?
}

struct UpdateSmartScopePayload: Codable, Sendable, Equatable {
    var `name`: String?
    var `icon`: String?
    var `filter`: GroupRule?
    var `defaultSort`: [SortSpec]?
    var `isPublic`: Bool?
    var `syncToKobo`: Bool?
}

struct SetSmartScopeKoboSyncPayload: Codable, Sendable, Equatable {
    var `enabled`: Bool
}

struct SavedView: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `name`: String
    var `layout`: TableLayoutState
    var `sort`: [SortSpec]
    var `filter`: GroupRule?
    var `favorite`: Bool?
}

struct TableLayoutState: Codable, Sendable, Equatable {
    var `columnOrder`: [String]
    var `hiddenColumns`: [String]
    var `columnWidths`: [String: Double]
    var `pinnedColumns`: [String: String?]?
}

struct TablePreset: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `name`: String
    var `layout`: TableLayoutState
    var `sort`: [SortSpec]?
    var `isBuiltIn`: Bool?
    var `favorite`: Bool?
}

struct TableViewBackup: Codable, Sendable, Equatable {
    var `version`: Int
    var `presets`: [TablePreset]
    var `savedViews`: [SavedView]
}

struct MetadataCandidate: Codable, Sendable, Equatable {
    var `provider`: String
    var `providerId`: String
    var `hardcoverEditionId`: String?
    var `title`: String?
    var `displayTitle`: String?
    var `subtitle`: String?
    var `authors`: [String]?
    var `description`: String?
    var `publisher`: String?
    var `publishedDate`: String?
    var `publishedYear`: Int?
    var `language`: String?
    var `pageCount`: Int?
    var `isbn10`: String?
    var `isbn13`: String?
    var `seriesName`: String?
    var `seriesIndex`: String?
    var `seriesTotalBooks`: Double?
    var `seriesMemberships`: [MetadataSeriesMembership]?
    var `genres`: [String]?
    var `coverUrl`: String?
    var `coverShape`: String?
    var `coverWidth`: Double?
    var `coverHeight`: Double?
    var `sourceUrl`: String?
    var `narrators`: [String]?
    var `durationSeconds`: Int?
    var `abridged`: Bool?
    var `audibleId`: String?
    var `chapters`: [AudiobookChapter]?
    var `comicMetadata`: ComicMetadataFields?
    var `communityRating`: Double?
    var `communityRatingCount`: Int?
}

struct MetadataSeriesMembership: Codable, Sendable, Equatable {
    var `seriesName`: String
    var `seriesIndex`: String?
}

struct BookFileMetadataResponse: Codable, Sendable, Equatable {
    var `publisher`: FieldUpdate<String>?
    var `language`: FieldUpdate<String>?
    var `pageCount`: FieldUpdate<Int>?
    var `genres`: [String]?
    var `description`: FieldUpdate<String>?
    var `googleBooksId`: FieldUpdate<String>?
    var `goodreadsId`: FieldUpdate<String>?
    var `amazonId`: FieldUpdate<String>?
    var `hardcoverId`: FieldUpdate<String>?
    var `hardcoverEditionId`: FieldUpdate<String>?
    var `openLibraryId`: FieldUpdate<String>?
    var `itunesId`: FieldUpdate<String>?
    var `audibleId`: FieldUpdate<String>?
    var `librofmId`: FieldUpdate<String>?
    var `koboId`: FieldUpdate<String>?
    var `comicvineId`: FieldUpdate<String>?
    var `ranobedbId`: FieldUpdate<String>?
    var `lubimyczytacId`: FieldUpdate<String>?
    var `aladinId`: FieldUpdate<String>?
    var `title`: FieldUpdate<String>?
    var `subtitle`: FieldUpdate<String>?
    var `authors`: [String]?
    var `publishedYear`: FieldUpdate<Int>?
    var `seriesName`: FieldUpdate<String>?
    var `seriesIndex`: FieldUpdate<String>?
    var `isbn13`: FieldUpdate<String>?
    var `isbn10`: FieldUpdate<String>?
    var `publishedDate`: FieldUpdate<String>?
    var `narrators`: [String]?
    var `durationSeconds`: FieldUpdate<Int>?
    var `customMetadata`: [CustomMetadataBookValueInput]?
    var `comicMetadata`: BookFileComicMetadata?
}

struct BookFileComicMetadata: Codable, Sendable, Equatable {
    var `pencillers`: [String]?
    var `inkers`: [String]?
    var `colorists`: [String]?
    var `letterers`: [String]?
    var `coverArtists`: [String]?
    var `characters`: [String]?
    var `teams`: [String]?
    var `locations`: [String]?
    var `storyArcs`: [String]?
    var `issueNumber`: FieldUpdate<String>?
    var `volumeName`: FieldUpdate<String>?
}

struct BookMetadataRefreshPreviewResponse: Codable, Sendable, Equatable {
    var `metadata`: BookMetadataRefreshPreviewFields
    var `diagnostics`: MetadataFetchDiagnostics
}

struct BookMetadataRefreshPreviewFields: Codable, Sendable, Equatable {
    var `isbn10`: FieldUpdate<String>?
    var `isbn13`: FieldUpdate<String>?
    var `title`: FieldUpdate<String>?
    var `subtitle`: FieldUpdate<String>?
    var `description`: FieldUpdate<String>?
    var `authors`: [String]?
    var `genres`: [String]?
    var `publisher`: FieldUpdate<String>?
    var `publishedDate`: FieldUpdate<String>?
    var `publishedYear`: FieldUpdate<Int>?
    var `language`: FieldUpdate<String>?
    var `pageCount`: FieldUpdate<Int>?
    var `seriesName`: FieldUpdate<String>?
    var `seriesIndex`: FieldUpdate<String>?
    var `seriesMemberships`: FieldUpdate<[MetadataSeriesMembership]>?
    var `communityRatings`: [BookCommunityRating]?
    var `coverUrl`: String?
    var `audioCoverUrl`: String?
    var `googleBooksId`: FieldUpdate<String>?
    var `goodreadsId`: FieldUpdate<String>?
    var `amazonId`: FieldUpdate<String>?
    var `hardcoverId`: FieldUpdate<String>?
    var `hardcoverEditionId`: FieldUpdate<String>?
    var `openLibraryId`: FieldUpdate<String>?
    var `itunesId`: FieldUpdate<String>?
    var `audibleId`: FieldUpdate<String>?
    var `librofmId`: FieldUpdate<String>?
    var `koboId`: FieldUpdate<String>?
    var `comicvineId`: FieldUpdate<String>?
    var `ranobedbId`: FieldUpdate<String>?
    var `lubimyczytacId`: FieldUpdate<String>?
    var `aladinId`: FieldUpdate<String>?
    var `audioMetadata`: BookMetadataRefreshPreviewFieldsAudioMetadata?
    var `comicMetadata`: ComicMetadataFields?
}

struct BookMetadataRefreshPreviewFieldsAudioMetadata: Codable, Sendable, Equatable {
    var `narrators`: [String]?
    var `durationSeconds`: FieldUpdate<Int>?
    var `abridged`: FieldUpdate<Bool>?
    var `chapters`: [AudiobookChapter]?
}

struct MetadataFetchDiagnostics: Codable, Sendable, Equatable {
    var `reason`: String?
    var `activeProviders`: [String]
    var `fieldRuleProviders`: [String]
    var `disabledFieldRuleProviders`: [String]
    var `enabledUnreferencedProviders`: [String]
    var `throttledProviders`: [String]
    var `candidateProviders`: [String]
    var `candidateCount`: Double
    var `resolvedFieldCount`: Double
    var `coverSlots`: MetadataFetchDiagnosticsCoverSlots?
}

struct MetadataFetchDiagnosticsCoverSlots: Codable, Sendable, Equatable {
    var `ebook`: MetadataFetchCoverSlotDiagnostics?
    var `audio`: MetadataFetchCoverSlotDiagnostics?
}

struct MetadataFetchCoverSlotDiagnostics: Codable, Sendable, Equatable {
    var `provider`: String?
    var `pass`: Double?
}

struct MetadataProviderInfo: Codable, Sendable, Equatable {
    var `key`: String
    var `label`: String
    var `identifiable`: Bool
    var `selectedByFieldRules`: Bool?
    var `coverPriority`: Double?
    var `audioCoverPriority`: Double?
}

struct MetadataProviderSearchStatus: Codable, Sendable, Equatable {
    var `provider`: String
    var `outcome`: String
}

struct UploadCoverFromUrlPayload: Codable, Sendable, Equatable {
    var `url`: String
}

struct CoverSearchResult: Codable, Sendable, Equatable {
    var `url`: CoverSearchResultUrl
    var `previewUrl`: String
    var `sourceUrl`: String
    var `width`: Int
    var `height`: Int
    var `source`: String
}

enum CoverSearchResultUrl: Codable, Sendable, Equatable {
    case string(String)
    case number(Double)

    init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) { self = .string(value); return }
        if let value = try? container.decode(Double.self) { self = .number(value); return }
        throw DecodingError.typeMismatch(Self.self, .init(codingPath: decoder.codingPath, debugDescription: "Invalid filter value"))
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        }
    }
}

struct PdfReaderSettings: Codable, Sendable, Equatable {
    var `scrollMode`: String
    var `spread`: String
    var `zoomMode`: String
    var `customScale`: Double
    var `rotation`: Int
}

struct CbxReaderSettings: Codable, Sendable, Equatable {
    var `fitMode`: String
    var `viewMode`: String
    var `scrollMode`: String
    var `direction`: String
    var `spreadAlignment`: String
    var `spreadGap`: Int
    var `forceTwoPage`: Bool
    var `widePageSingletonMode`: String
    var `bgColor`: String
    var `autoAdvance`: Bool
}

struct PdfReaderSettingsPatch: Codable, Sendable, Equatable {
    var `scrollMode`: String?
    var `spread`: String?
    var `zoomMode`: String?
    var `customScale`: Double?
    var `rotation`: Int?
}

struct CbxReaderSettingsPatch: Codable, Sendable, Equatable {
    var `fitMode`: String?
    var `viewMode`: String?
    var `scrollMode`: String?
    var `direction`: String?
    var `spreadAlignment`: String?
    var `spreadGap`: Int?
    var `forceTwoPage`: Bool?
    var `widePageSingletonMode`: String?
    var `bgColor`: String?
    var `autoAdvance`: Bool?
}

struct PdfReaderPreferenceResponse: Codable, Sendable, Equatable {
    var `settings`: PdfReaderPreferenceResponseSettings?
    var `isCustomized`: Bool
}

struct PdfReaderPreferenceResponseSettings: Codable, Sendable, Equatable {
    var `scrollMode`: String?
    var `spread`: String?
    var `zoomMode`: String?
    var `customScale`: Double?
    var `rotation`: Int?
}

struct CbxReaderPreferenceResponse: Codable, Sendable, Equatable {
    var `settings`: CbxReaderPreferenceResponseSettings?
    var `isCustomized`: Bool
}

struct CbxReaderPreferenceResponseSettings: Codable, Sendable, Equatable {
    var `fitMode`: String?
    var `viewMode`: String?
    var `scrollMode`: String?
    var `direction`: String?
    var `spreadAlignment`: String?
    var `spreadGap`: Int?
    var `forceTwoPage`: Bool?
    var `widePageSingletonMode`: String?
    var `bgColor`: String?
    var `autoAdvance`: Bool?
}

struct FixedReaderDefaultsResponse: Codable, Sendable, Equatable {
    var `pdf`: FixedReaderDefaultsResponsePdf?
    var `cbx`: FixedReaderDefaultsResponseCbx?
}

struct FixedReaderDefaultsResponsePdf: Codable, Sendable, Equatable {
    var `scrollMode`: String?
    var `spread`: String?
    var `zoomMode`: String?
    var `customScale`: Double?
    var `rotation`: Int?
}

struct FixedReaderDefaultsResponseCbx: Codable, Sendable, Equatable {
    var `fitMode`: String?
    var `viewMode`: String?
    var `scrollMode`: String?
    var `direction`: String?
    var `spreadAlignment`: String?
    var `spreadGap`: Int?
    var `forceTwoPage`: Bool?
    var `widePageSingletonMode`: String?
    var `bgColor`: String?
    var `autoAdvance`: Bool?
}

struct EpubReaderSettings: Codable, Sendable, Equatable {
    var `themeName`: String
    var `isDark`: Bool
    var `fontFamily`: String?
    var `fontWeight`: Double
    var `fontStyle`: String
    var `fontSize`: Double
    var `lineHeight`: Double
    var `paragraphSpacing`: Double
    var `letterSpacing`: Double?
    var `wordSpacing`: Double?
    var `textIndent`: Double?
    var `maxColumnCount`: Double
    var `gap`: Double
    var `maxInlineSize`: Double
    var `maxBlockSize`: Double
    var `justify`: Bool
    var `hyphenate`: Bool
    var `flow`: String
    var `overrideBookFormatting`: Bool
    var `footerDisplayMode`: Double
    var `fixedLayoutSpread`: String
}

struct EpubReaderSettingsPatch: Codable, Sendable, Equatable {
    var `themeName`: String?
    var `isDark`: Bool?
    var `fontFamily`: FieldUpdate<String>?
    var `fontWeight`: Double?
    var `fontStyle`: String?
    var `fontSize`: Double?
    var `lineHeight`: Double?
    var `paragraphSpacing`: Double?
    var `letterSpacing`: FieldUpdate<Double>?
    var `wordSpacing`: FieldUpdate<Double>?
    var `textIndent`: FieldUpdate<Double>?
    var `maxColumnCount`: Double?
    var `gap`: Double?
    var `maxInlineSize`: Double?
    var `maxBlockSize`: Double?
    var `justify`: Bool?
    var `hyphenate`: Bool?
    var `flow`: String?
    var `overrideBookFormatting`: Bool?
    var `footerDisplayMode`: Double?
    var `fixedLayoutSpread`: String?
}

struct EpubReaderDefaultsResponse: Codable, Sendable, Equatable {
    var `epub`: EpubReaderDefaultsResponseEpub?
}

struct EpubReaderDefaultsResponseEpub: Codable, Sendable, Equatable {
    var `themeName`: String?
    var `isDark`: Bool?
    var `fontFamily`: FieldUpdate<String>?
    var `fontWeight`: Double?
    var `fontStyle`: String?
    var `fontSize`: Double?
    var `lineHeight`: Double?
    var `paragraphSpacing`: Double?
    var `letterSpacing`: FieldUpdate<Double>?
    var `wordSpacing`: FieldUpdate<Double>?
    var `textIndent`: FieldUpdate<Double>?
    var `maxColumnCount`: Double?
    var `gap`: Double?
    var `maxInlineSize`: Double?
    var `maxBlockSize`: Double?
    var `justify`: Bool?
    var `hyphenate`: Bool?
    var `flow`: String?
    var `overrideBookFormatting`: Bool?
    var `footerDisplayMode`: Double?
    var `fixedLayoutSpread`: String?
}

struct EpubReaderDefaultsPatchBody: Codable, Sendable, Equatable {
    var `set`: EpubReaderDefaultsPatchBodySet
}

struct EpubReaderDefaultsPatchBodySet: Codable, Sendable, Equatable {
    var `themeName`: String?
    var `isDark`: Bool?
    var `fontFamily`: String?
    var `fontWeight`: Double?
    var `fontStyle`: String?
    var `fontSize`: Double?
    var `lineHeight`: Double?
    var `paragraphSpacing`: Double?
    var `letterSpacing`: Double?
    var `wordSpacing`: Double?
    var `textIndent`: Double?
    var `maxColumnCount`: Double?
    var `gap`: Double?
    var `maxInlineSize`: Double?
    var `maxBlockSize`: Double?
    var `justify`: Bool?
    var `hyphenate`: Bool?
    var `flow`: String?
    var `overrideBookFormatting`: Bool?
    var `footerDisplayMode`: Double?
    var `fixedLayoutSpread`: String?
}

struct EpubReaderPreferenceResponse: Codable, Sendable, Equatable {
    var `settings`: EpubReaderPreferenceResponseSettings?
    var `isCustomized`: Bool
}

struct EpubReaderPreferenceResponseSettings: Codable, Sendable, Equatable {
    var `themeName`: String?
    var `isDark`: Bool?
    var `fontFamily`: FieldUpdate<String>?
    var `fontWeight`: Double?
    var `fontStyle`: String?
    var `fontSize`: Double?
    var `lineHeight`: Double?
    var `paragraphSpacing`: Double?
    var `letterSpacing`: FieldUpdate<Double>?
    var `wordSpacing`: FieldUpdate<Double>?
    var `textIndent`: FieldUpdate<Double>?
    var `maxColumnCount`: Double?
    var `gap`: Double?
    var `maxInlineSize`: Double?
    var `maxBlockSize`: Double?
    var `justify`: Bool?
    var `hyphenate`: Bool?
    var `flow`: String?
    var `overrideBookFormatting`: Bool?
    var `footerDisplayMode`: Double?
    var `fixedLayoutSpread`: String?
}

struct EpubReaderSettingsBody: Codable, Sendable, Equatable {
    var `settings`: EpubReaderSettings
}

struct EpubReaderPreferencePatchBody: Codable, Sendable, Equatable {
    var `set`: EpubReaderPreferencePatchBodySet?
    var `unset`: [String]?
}

struct EpubReaderPreferencePatchBodySet: Codable, Sendable, Equatable {
    var `themeName`: String?
    var `isDark`: Bool?
    var `fontFamily`: String?
    var `fontWeight`: Double?
    var `fontStyle`: String?
    var `fontSize`: Double?
    var `lineHeight`: Double?
    var `paragraphSpacing`: Double?
    var `letterSpacing`: Double?
    var `wordSpacing`: Double?
    var `textIndent`: Double?
    var `maxColumnCount`: Double?
    var `gap`: Double?
    var `maxInlineSize`: Double?
    var `maxBlockSize`: Double?
    var `justify`: Bool?
    var `hyphenate`: Bool?
    var `flow`: String?
    var `overrideBookFormatting`: Bool?
    var `footerDisplayMode`: Double?
    var `fixedLayoutSpread`: String?
}

struct UserFont: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `familyName`: String
    var `originalFileName`: String
    var `format`: String
    var `weight`: Double
    var `style`: String
    var `weightMin`: Double?
    var `weightMax`: Double?
    var `instances`: [FontNamedInstance]?
    var `fileSize`: Int
    var `createdAt`: String
}

struct FontNamedInstance: Codable, Sendable, Equatable {
    var `weight`: Double
    var `style`: String
    var `name`: String?
}

struct ServerFontPreferencesResponse: Codable, Sendable, Equatable {
    var `settings`: ServerFontPreferences?
}

struct ServerFontPreferences: Codable, Sendable, Equatable {
    var `hiddenFamilies`: [String]
}

struct ServerFontPreferencesBody: Codable, Sendable, Equatable {
    var `settings`: ServerFontPreferences
}

struct AudioReaderSettings: Codable, Sendable, Equatable {
    var `playbackSpeed`: Double
    var `volume`: Double
    var `skipBackSeconds`: Double
    var `skipForwardSeconds`: Double
}

struct AudioReaderDefaultsResponse: Codable, Sendable, Equatable {
    var `audio`: AudioReaderDefaultsResponseAudio?
}

struct AudioReaderDefaultsResponseAudio: Codable, Sendable, Equatable {
    var `playbackSpeed`: Double?
    var `volume`: Double?
    var `skipBackSeconds`: Double?
    var `skipForwardSeconds`: Double?
}

struct AudioReaderDefaultsPatchBody: Codable, Sendable, Equatable {
    var `set`: AudioReaderDefaultsPatchBodySet
}

struct AudioReaderDefaultsPatchBodySet: Codable, Sendable, Equatable {
    var `playbackSpeed`: Double?
    var `volume`: Double?
    var `skipBackSeconds`: Double?
    var `skipForwardSeconds`: Double?
}

struct PdfReaderPreferencePatchBody: Codable, Sendable, Equatable {
    var `set`: PdfReaderPreferencePatchBodySet?
    var `unset`: [String]?
}

struct PdfReaderPreferencePatchBodySet: Codable, Sendable, Equatable {
    var `scrollMode`: String?
    var `spread`: String?
    var `zoomMode`: String?
    var `customScale`: Double?
    var `rotation`: Int?
}

struct CbxReaderPreferencePatchBody: Codable, Sendable, Equatable {
    var `set`: CbxReaderPreferencePatchBodySet?
    var `unset`: [String]?
}

struct CbxReaderPreferencePatchBodySet: Codable, Sendable, Equatable {
    var `fitMode`: String?
    var `viewMode`: String?
    var `scrollMode`: String?
    var `direction`: String?
    var `spreadAlignment`: String?
    var `spreadGap`: Int?
    var `forceTwoPage`: Bool?
    var `widePageSingletonMode`: String?
    var `bgColor`: String?
    var `autoAdvance`: Bool?
}

struct PdfReaderDefaultsPatchBody: Codable, Sendable, Equatable {
    var `set`: PdfReaderDefaultsPatchBodySet
}

struct PdfReaderDefaultsPatchBodySet: Codable, Sendable, Equatable {
    var `scrollMode`: String?
    var `spread`: String?
    var `zoomMode`: String?
    var `customScale`: Double?
    var `rotation`: Int?
}

struct CbxReaderDefaultsPatchBody: Codable, Sendable, Equatable {
    var `set`: CbxReaderDefaultsPatchBodySet
}

struct CbxReaderDefaultsPatchBodySet: Codable, Sendable, Equatable {
    var `fitMode`: String?
    var `viewMode`: String?
    var `scrollMode`: String?
    var `direction`: String?
    var `spreadAlignment`: String?
    var `spreadGap`: Int?
    var `forceTwoPage`: Bool?
    var `widePageSingletonMode`: String?
    var `bgColor`: String?
    var `autoAdvance`: Bool?
}

struct BookmarkResponse: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `bookId`: Int
    var `cfi`: String?
    var `title`: String
    var `positionSeconds`: Double?
    var `fileId`: Int?
    var `pageNumber`: Int?
    var `createdAt`: String
}

struct BookmarksPage: Codable, Sendable, Equatable {
    var `items`: [BookmarkResponse]
    var `nextCursor`: Int?
}

struct EpubBookmarkNavigationItem: Codable, Sendable, Equatable, Identifiable {
    var `chapterTitle`: String?
    var `contextPercentage`: Int?
    var `locationLabel`: String
    var `id`: Int
    var `bookId`: Int
    var `cfi`: String?
    var `title`: String
    var `positionSeconds`: Double?
    var `fileId`: Int?
    var `pageNumber`: Int?
    var `createdAt`: String
}

struct EpubBookmarkNavigationPage: Codable, Sendable, Equatable {
    var `bookId`: Int
    var `fileId`: Int
    var `fileRevision`: String
    var `query`: String
    var `sort`: String
    var `items`: [EpubBookmarkNavigationItem]
    var `nextCursor`: String?
    var `currentBookmarkId`: Int?
    var `scannedCount`: Int
    var `scanLimited`: Bool
}

struct CreateFixedPageBookmarkPayload: Codable, Sendable, Equatable {
    var `clientId`: String?
    var `fileId`: Int
    var `pageNumber`: Int
    var `title`: String
}

struct CreateEpubBookmarkPayload: Codable, Sendable, Equatable {
    var `clientId`: String?
    var `cfi`: String
    var `title`: String
}

struct SetBookReadingStatusPayload: Encodable, Sendable, Equatable {
    var `status`: String?
    var `startedAt`: FieldUpdate<String>?
    var `finishedAt`: FieldUpdate<String>?
}

struct UpdateBookPersonalNotePayload: Encodable, Sendable, Equatable {
    var `note`: FieldUpdate<String>?
}

struct UpdateBookFilePayload: Encodable, Sendable, Equatable {
    var `filename`: String?
}

struct TtsPosition: Codable, Sendable, Equatable {
    var `cfi`: String
    var `chapterIndex`: Int?
    var `version`: String?
}

struct TtsPositionSnapshot: Codable, Sendable, Equatable {
    var `position`: TtsPosition?
    var `version`: String
}

struct SaveTtsPositionPayload: Encodable, Sendable, Equatable {
    var `cfi`: String
    var `chapterIndex`: Int?
    var `baseVersion`: String?
}

struct ClearTtsPositionQuery: Encodable, Sendable, Equatable {
    var `baseVersion`: String?
}

struct TtsUserPreferences: Codable, Sendable, Equatable {
    var `providerId`: String?
    var `voiceId`: String?
    var `speed`: Double
}

struct TtsEffectivePreferences: Codable, Sendable, Equatable {
    var `providerId`: String?
    var `voiceId`: String?
    var `speed`: Double
    var `isBookOverride`: Bool
}

struct TtsSpeedPreferencesPatch: Codable, Sendable, Equatable {
    var `speed`: Double
}

struct TtsPreferencesPatch: Codable, Sendable, Equatable {
    var `providerId`: String?
    var `voiceId`: String?
    var `speed`: Double?
}

struct TtsVoicePreviewRequest: Codable, Sendable, Equatable {
    var `providerId`: String
    var `voiceId`: String
}

struct TtsProviderInfo: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `name`: String
    var `type`: String
}

struct TtsVoice: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `name`: String
    var `shortName`: String
    var `language`: String
    var `locale`: String
    var `gender`: String
    var `providerId`: String
    var `providerName`: String
}

struct TtsSynthesisRequest: Codable, Sendable, Equatable {
    var `text`: String
    var `voiceId`: String
    var `providerId`: String
    var `speed`: Double
    var `format`: String?
}

struct TtsCaptionedSpeech: Codable, Sendable, Equatable {
    var `audio`: String
    var `format`: String
    var `words`: [TtsWordTiming]
}

struct TtsWordTiming: Codable, Sendable, Equatable {
    var `word`: String
    var `startTime`: Double
    var `endTime`: Double
}

struct NativeTtsVoiceSettings: Codable, Sendable, Equatable {
    var `voiceIdentifier`: String?
    var `useServer`: Bool?
}

struct UserDashboardSettingsResponse: Codable, Sendable, Equatable {
    var `settings`: UserSettings
}

struct UserReaderSettingsResponse: Codable, Sendable, Equatable {
    var `settings`: UserSettings
    var `permissions`: [String]
}

extension EpubReaderSettings {
    static var readerDefault: Self { Self(themeName: "default", isDark: false, fontFamily: nil, fontWeight: 400, fontStyle: "normal", fontSize: 16, lineHeight: 1.5, paragraphSpacing: 0, letterSpacing: nil, wordSpacing: nil, textIndent: nil, maxColumnCount: 2, gap: 0.05, maxInlineSize: 720, maxBlockSize: 1440, justify: true, hyphenate: true, flow: "paginated", overrideBookFormatting: true, footerDisplayMode: 0, fixedLayoutSpread: "auto") }
}

extension AudioReaderSettings {
    static var readerDefault: Self { Self(playbackSpeed: 1, volume: 1, skipBackSeconds: 10, skipForwardSeconds: 30) }
}

extension PdfReaderSettings {
    static var readerDefault: Self { Self(scrollMode: "page", spread: "none", zoomMode: "fit-page", customScale: 1, rotation: 0) }
}

extension CbxReaderSettings {
    static var readerDefault: Self { Self(fitMode: "fit-page", viewMode: "single", scrollMode: "paginated", direction: "ltr", spreadAlignment: "normal", spreadGap: 0, forceTwoPage: false, widePageSingletonMode: "auto", bgColor: "black", autoAdvance: false) }
}

enum ReaderFontVocabulary {
    static let fileMaximum = 52428800
    static let userMaximum = 50
    static let serverMaximum = 200
    static let familyNameMaximum = 200
    static let prefixes: [String: String] = ["user": "__userfont_", "server": "__serverfont_"]
    static let mimeTypes: [String: String] = ["ttf": "font/ttf", "otf": "font/otf", "woff": "font/woff", "woff2": "font/woff2"]
    static let cssFormats: [String: String] = ["ttf": "truetype", "otf": "opentype", "woff": "woff", "woff2": "woff2"]
    static func familyGroupName(_ name: String, scope: String) -> String {
        let safe = name.lowercased().replacingOccurrences(of: "[^a-z0-9]+", with: "_", options: .regularExpression).trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        return (prefixes[scope] ?? "") + (safe.isEmpty ? "font" : safe)
    }
}

enum NativeEbookVocabulary {
  static let mimeTypes: [String: String] = [
    "epub": "application/epub+zip",
    "mobi": "application/x-mobipocket-ebook",
    "azw3": "application/vnd.amazon.ebook",
    "azw": "application/vnd.amazon.ebook",
    "fb2": "application/x-fictionbook+xml",
  ]
}

enum EPUBThemeVocabulary {
    static let names: [String] = ["default", "gray", "sepia", "crimson", "meadow", "rosewood", "azure", "dawnlight", "ember", "aurora", "ocean", "mist", "amoled"]
}

enum BookFileVocabulary {
    static let formats: [String] = ["pdf", "epub", "fb2", "cbz", "cb7", "mobi", "azw3", "azw", "m4b", "m4a", "mp3", "flac", "kepub", "cbr", "opus", "ogg"]
}

enum AudiobookVocabulary {
    static let schema = "bookorbit.audiobook-manifest"
    static let version = 2
}

enum BookReadingVocabulary {
    static let statuses: [String] = ["unread", "want_to_read", "reading", "on_hold", "rereading", "read", "skimmed", "abandoned"]
    static let noteMaximum = 10000
}

enum AnnotationVocabulary {
    static let cfiMaximum = 2000
}

enum ReaderLayoutBounds {
    static let spreadGapMinimum = 0
    static let spreadGapMaximum = 64
    static let widePageRatio = 1.2
}

enum MetadataVocabulary {
    static let coverProviders: [String] = ["duckduckgo", "itunes", "audiobookcovers", "all"]
    static let lockFields: [String] = ["title", "subtitle", "authors", "description", "publisher", "publishedYear", "language", "pageCount", "seriesName", "seriesIndex", "isbn13", "isbn10", "genres", "tags", "rating", "communityRating", "narrators", "durationSeconds", "abridged", "googleBooksId", "goodreadsId", "amazonId", "hardcoverId", "hardcoverEditionId", "openLibraryId", "itunesId", "audibleId", "librofmId", "koboId", "comicvineId", "ranobedbId", "lubimyczytacId", "aladinId", "comicIssueNumber", "comicVolumeName", "comicStoryArcs", "comicPencillers", "comicInkers", "comicColorists", "comicLetterers", "comicCoverArtists", "comicCharacters", "comicTeams", "comicLocations", "cover", "audioCover"]
    static let providers: [String] = ["kobo", "google", "goodreads", "amazon", "hardcover", "openLibrary", "itunes", "audible", "audnexus", "librofm", "comicvine", "ranobedb", "lubimyczytac", "aladin"]
    static let statusEvent = "provider-status"
}

@MainActor struct MetadataProviderField: Identifiable {
    let id: String
    let provider: String
    let maximum: Int
    let read: KeyPath<BookDetail, String?>
    let write: WritableKeyPath<BookMetadataUpdatePayload, FieldUpdate<String>?>
    let preview: KeyPath<BookMetadataRefreshPreviewFields, FieldUpdate<String>?>
    let file: KeyPath<BookFileMetadataResponse, FieldUpdate<String>?>

    static let byProvider: [String: String] = ["google": "googleBooksId", "goodreads": "goodreadsId", "amazon": "amazonId", "hardcover": "hardcoverId", "openLibrary": "openLibraryId", "itunes": "itunesId", "audible": "audibleId", "audnexus": "audibleId", "librofm": "librofmId", "comicvine": "comicvineId", "ranobedb": "ranobedbId", "kobo": "koboId", "lubimyczytac": "lubimyczytacId", "aladin": "aladinId"]

    static let fields: [MetadataProviderField] = [
        .init(id: "googleBooksId", provider: "google", maximum: 50, read: \BookDetail.providerIds.google, write: \BookMetadataUpdatePayload.googleBooksId, preview: \BookMetadataRefreshPreviewFields.googleBooksId, file: \BookFileMetadataResponse.googleBooksId),
        .init(id: "goodreadsId", provider: "goodreads", maximum: 50, read: \BookDetail.providerIds.goodreads, write: \BookMetadataUpdatePayload.goodreadsId, preview: \BookMetadataRefreshPreviewFields.goodreadsId, file: \BookFileMetadataResponse.goodreadsId),
        .init(id: "amazonId", provider: "amazon", maximum: 20, read: \BookDetail.providerIds.amazon, write: \BookMetadataUpdatePayload.amazonId, preview: \BookMetadataRefreshPreviewFields.amazonId, file: \BookFileMetadataResponse.amazonId),
        .init(id: "hardcoverId", provider: "hardcover", maximum: 255, read: \BookDetail.providerIds.hardcover, write: \BookMetadataUpdatePayload.hardcoverId, preview: \BookMetadataRefreshPreviewFields.hardcoverId, file: \BookFileMetadataResponse.hardcoverId),
        .init(id: "hardcoverEditionId", provider: "hardcover", maximum: 50, read: \BookDetail.hardcoverEditionId, write: \BookMetadataUpdatePayload.hardcoverEditionId, preview: \BookMetadataRefreshPreviewFields.hardcoverEditionId, file: \BookFileMetadataResponse.hardcoverEditionId),
        .init(id: "openLibraryId", provider: "openLibrary", maximum: 50, read: \BookDetail.providerIds.openLibrary, write: \BookMetadataUpdatePayload.openLibraryId, preview: \BookMetadataRefreshPreviewFields.openLibraryId, file: \BookFileMetadataResponse.openLibraryId),
        .init(id: "itunesId", provider: "itunes", maximum: 50, read: \BookDetail.providerIds.itunes, write: \BookMetadataUpdatePayload.itunesId, preview: \BookMetadataRefreshPreviewFields.itunesId, file: \BookFileMetadataResponse.itunesId),
        .init(id: "audibleId", provider: "audible", maximum: 20, read: \BookDetail.providerIds.audible, write: \BookMetadataUpdatePayload.audibleId, preview: \BookMetadataRefreshPreviewFields.audibleId, file: \BookFileMetadataResponse.audibleId),
        .init(id: "librofmId", provider: "librofm", maximum: 50, read: \BookDetail.providerIds.librofm, write: \BookMetadataUpdatePayload.librofmId, preview: \BookMetadataRefreshPreviewFields.librofmId, file: \BookFileMetadataResponse.librofmId),
        .init(id: "koboId", provider: "kobo", maximum: 255, read: \BookDetail.providerIds.kobo, write: \BookMetadataUpdatePayload.koboId, preview: \BookMetadataRefreshPreviewFields.koboId, file: \BookFileMetadataResponse.koboId),
        .init(id: "comicvineId", provider: "comicvine", maximum: 50, read: \BookDetail.providerIds.comicvine, write: \BookMetadataUpdatePayload.comicvineId, preview: \BookMetadataRefreshPreviewFields.comicvineId, file: \BookFileMetadataResponse.comicvineId),
        .init(id: "ranobedbId", provider: "ranobedb", maximum: 50, read: \BookDetail.providerIds.ranobedb, write: \BookMetadataUpdatePayload.ranobedbId, preview: \BookMetadataRefreshPreviewFields.ranobedbId, file: \BookFileMetadataResponse.ranobedbId),
        .init(id: "lubimyczytacId", provider: "lubimyczytac", maximum: 512, read: \BookDetail.providerIds.lubimyczytac, write: \BookMetadataUpdatePayload.lubimyczytacId, preview: \BookMetadataRefreshPreviewFields.lubimyczytacId, file: \BookFileMetadataResponse.lubimyczytacId),
        .init(id: "aladinId", provider: "aladin", maximum: 20, read: \BookDetail.providerIds.aladin, write: \BookMetadataUpdatePayload.aladinId, preview: \BookMetadataRefreshPreviewFields.aladinId, file: \BookFileMetadataResponse.aladinId),
    ]
}

enum FilterVocabulary {
    static let operators: [String: [String]] = [
        "title": ["contains", "notContains", "startsWith", "endsWith", "eq", "notEq", "isEmpty", "isNotEmpty"],
        "publisher": ["contains", "notContains", "eq", "notEq", "includesAny", "excludesAll", "isEmpty", "isNotEmpty"],
        "language": ["eq", "notEq", "includesAny", "excludesAll", "isEmpty", "isNotEmpty"],
        "series": ["contains", "notContains", "eq", "notEq", "includesAny", "excludesAll", "isEmpty", "isNotEmpty"],
        "author": ["includesAny", "includesAll", "excludesAll", "isEmpty", "isNotEmpty"],
        "genre": ["includesAny", "includesAll", "excludesAll", "isEmpty", "isNotEmpty"],
        "tag": ["includesAny", "includesAll", "excludesAll", "isEmpty", "isNotEmpty"],
        "collection": ["includesAny", "excludesAll", "isEmpty", "isNotEmpty"],
        "library": ["includesAny", "excludesAll"],
        "format": ["includesAny", "excludesAll"],
        "fileSize": ["eq", "notEq", "gt", "gte", "lt", "lte", "between", "isEmpty", "isNotEmpty"],
        "publishedDate": ["before", "after", "between", "withinLast", "isEmpty", "isNotEmpty"],
        "publishedYear": ["eq", "notEq", "gt", "gte", "lt", "lte", "between", "isEmpty", "isNotEmpty"],
        "seriesIndex": ["eq", "notEq", "gt", "gte", "lt", "lte", "between", "isEmpty", "isNotEmpty"],
        "pageCount": ["gt", "gte", "lt", "lte", "between", "isEmpty", "isNotEmpty"],
        "addedAt": ["before", "after", "between", "withinLast"],
        "startedAt": ["before", "after", "between", "withinLast", "isEmpty", "isNotEmpty"],
        "finishedAt": ["before", "after", "between", "withinLast", "isEmpty", "isNotEmpty"],
        "fileAvailability": ["isMissing", "isPresent"],
        "rating": ["eq", "gt", "gte", "lt", "lte", "isEmpty", "isNotEmpty"],
        "communityRating": ["eq", "notEq", "gt", "gte", "lt", "lte", "between", "isEmpty", "isNotEmpty"],
        "communityRatingCount": ["eq", "notEq", "gt", "gte", "lt", "lte", "between", "isEmpty", "isNotEmpty"],
        "readProgress": ["isUnread", "isInProgress", "isFinished"],
        "readStatus": ["includesAny", "excludesAll", "isEmpty", "isNotEmpty"],
        "description": ["isEmpty", "isNotEmpty"],
        "isbn": ["isEmpty", "isNotEmpty", "eq"],
        "metadataScore": ["gt", "gte", "lt", "lte", "between", "isEmpty", "isNotEmpty"],
        "cover": ["isMissing", "isPresent"],
        "audioCover": ["isMissing", "isPresent"],
        "lockStatus": ["isLocked", "isUnlocked"],
        "seriesStatus": ["isUpNext"],
    ]
    static let ratingProviders: [String] = ["google", "goodreads", "amazon", "hardcover", "openLibrary", "itunes", "audible", "ranobedb", "any"]
    static let readStatuses: [String] = ["unread", "want_to_read", "reading", "on_hold", "rereading", "read", "skimmed", "abandoned"]
    static let formats: [String] = ["pdf", "epub", "fb2", "cbz", "cb7", "mobi", "azw3", "azw", "m4b", "m4a", "mp3", "flac", "kepub", "cbr", "opus", "ogg"]
}

enum NativeViewBackupVocabulary {
    static let customOperators: [String] = ["contains", "notContains", "startsWith", "endsWith", "eq", "notEq", "isEmpty", "isNotEmpty", "gt", "gte", "lt", "lte", "between", "before", "after", "withinLast", "isTrue", "isFalse"]
}

enum SortVocabulary {
    static let fields: [String] = ["relevance", "author", "title", "series", "seriesIndex", "addedAt", "updatedAt", "publishedDate", "publishedYear", "pageCount", "rating", "publisher", "fileSize", "readProgress", "readStatus", "format", "lastReadAt", "startedAt", "finishedAt", "random", "language", "metadataScore", "collectionOrder"]
}

enum NativeTranslationVocabulary {
    static let characterLimit = 500
    static let languages: [SupportedLanguage] = [
        .init(code: "en", name: "English"),
        .init(code: "es", name: "Spanish"),
        .init(code: "fr", name: "French"),
        .init(code: "de", name: "German"),
        .init(code: "zh", name: "Chinese"),
        .init(code: "ja", name: "Japanese"),
        .init(code: "ko", name: "Korean"),
        .init(code: "ar", name: "Arabic"),
        .init(code: "hi", name: "Hindi"),
        .init(code: "pt", name: "Portuguese"),
    ]
}

enum CollectionVocabulary {
    static let iconMaximum = 100
}

enum CoverMedium: String, Codable, Sendable, CaseIterable, Identifiable {
    case ebook
    case audio
    var id: String { rawValue }
}

enum Permission: String, Sendable {
    case `libraryDownload` = "library_download"
    case `libraryUpload` = "library_upload"
    case `libraryEditMetadata` = "library_edit_metadata"
    case `libraryDeleteBooks` = "library_delete_books"
    case `annotationManageOwn` = "annotation_manage_own"
    case `bookDockAccess` = "book_dock_access"
    case `bookRequestAccess` = "book_request_access"
    case `podcastManageFeeds` = "podcast_manage_feeds"
    case `podcastDownload` = "podcast_download"
    case `podcastEditMetadata` = "podcast_edit_metadata"
    case `podcastManageRetention` = "podcast_manage_retention"
    case `podcastPurge` = "podcast_purge"
    case `demoRestricted` = "demo_restricted"
    case `koboSync` = "kobo_sync"
    case `koreaderSync` = "koreader_sync"
    case `hardcoverSync` = "hardcover_sync"
    case `readwiseSync` = "readwise_sync"
    case `storygraphSync` = "storygraph_sync"
    case `opdsAccess` = "opds_access"
    case `emailSend` = "email_send"
    case `manageEmail` = "manage_email"
    case `manageLibraries` = "manage_libraries"
    case `manageMetadataConfig` = "manage_metadata_config"
    case `manageIcons` = "manage_icons"
    case `manageAppSettings` = "manage_app_settings"
    case `manageBookDock` = "manage_book_dock"
    case `manageBookRequests` = "manage_book_requests"
    case `bookRequestAutoApprove` = "book_request_auto_approve"
    case `bookRequestSelfFulfill` = "book_request_self_fulfill"
    case `manageUsers` = "manage_users"
    case `viewUserActivity` = "view_user_activity"
    case `viewAuditLog` = "view_audit_log"
    case `notificationAccess` = "notification_access"
}
