// Generated by scripts/ipad/generate-contracts.mjs from @bookorbit/types.
// Regenerate after shared contract changes.
import Foundation

struct NativeAuthResponse: Codable, Sendable, Equatable {
    var `user`: AuthUser
    var `accessToken`: String
    var `accessTokenExpiresAt`: String
    var `refreshToken`: String
    var `refreshTokenExpiresAt`: String
    var `sessionId`: Int
}

struct AuthUser: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `username`: String
    var `name`: String
    var `active`: Bool
    var `isSuperuser`: Bool
    var `isDefaultPassword`: Bool
    var `permissions`: [String]
}

struct NativeCredentials: Codable, Sendable, Equatable {
    var `accessToken`: String
    var `accessTokenExpiresAt`: String
    var `refreshToken`: String
    var `refreshTokenExpiresAt`: String
    var `sessionId`: Int
}

struct LoginRequest: Codable, Sendable, Equatable {
    var `username`: String
    var `password`: String
    var `clientKind`: String?
    var `deviceLabel`: String?
}

struct RefreshRequest: Codable, Sendable, Equatable {
    var `refreshToken`: String?
}

struct ChangePasswordRequest: Codable, Sendable, Equatable {
    var `currentPassword`: String
    var `newPassword`: String
}

struct OidcStateResponse: Codable, Sendable, Equatable {
    var `state`: String
    var `authorizationEndpoint`: String
}

struct OidcCallbackRequest: Codable, Sendable, Equatable {
    var `code`: String
    var `codeVerifier`: String
    var `redirectUri`: String
    var `nonce`: String
    var `state`: String
    var `clientKind`: String?
    var `deviceLabel`: String?
}

struct LoginOptionsResponse: Codable, Sendable, Equatable {
    var `passwordLoginEnabled`: Bool
    var `allowRegistration`: Bool
    var `oidcProviders`: [OidcProviderPublic]
}

struct OidcProviderPublic: Codable, Sendable, Equatable {
    var `slug`: String
    var `displayName`: String
    var `enabled`: Bool
    var `iconUrl`: String?
    var `clientId`: String
    var `scopes`: String
}

struct Library: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `type`: String
    var `accessLevel`: String?
    var `name`: String
    var `bookCount`: Int?
}

struct BooksPage: Codable, Sendable, Equatable {
    var `items`: [BookCard]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct BookCard: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `title`: String?
    var `authors`: [String]
    var `files`: [BookFileRef]
    var `hasCover`: Bool
    var `coverVersion`: String
    var `readingProgress`: Double?
    var `seriesName`: String?
}

struct BookFileRef: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `format`: String?
    var `role`: String
    var `sizeBytes`: Double?
    var `mediaOverlay`: EpubMediaOverlayCapability?
}

struct EpubMediaOverlayCapability: Codable, Sendable, Equatable {
    var `available`: Bool
    var `durationSeconds`: Double?
}

struct BookDetail: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `libraryId`: Int
    var `libraryName`: String
    var `title`: String?
    var `subtitle`: String?
    var `description`: String?
    var `publisher`: String?
    var `publishedDate`: String?
    var `publishedYear`: Int?
    var `language`: String?
    var `pageCount`: Int?
    var `isbn10`: String?
    var `isbn13`: String?
    var `authors`: [BookDetailAuthorsItem]
    var `genres`: [String]
    var `tags`: [String]
    var `files`: [BookDetailFile]
    var `lockedFields`: [String]
    var `coverMedia`: [CoverMedium]
    var `covers`: BookDetailCovers
    var `coverVersion`: String
}

struct BookDetailAuthorsItem: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `sortName`: String?
}

struct BookDetailFile: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `format`: String?
    var `role`: String
    var `filename`: String?
    var `sizeBytes`: Double?
    var `durationSeconds`: Double?
}

struct BookDetailCovers: Codable, Sendable, Equatable {
    var `ebook`: BookCoverSlot?
    var `audio`: BookCoverSlot?
}

struct BookCoverSlot: Codable, Sendable, Equatable {
    var `source`: String
    var `updatedAt`: String
    var `width`: Int?
    var `height`: Int?
}

struct BookQuery: Codable, Sendable, Equatable {
    var `sort`: [SortSpec]
    var `pagination`: BookQueryPagination
    var `q`: String?
    var `collapseSeries`: Bool?
}

struct SortSpec: Codable, Sendable, Equatable {
    var `field`: String
    var `dir`: String
}

struct BookQueryPagination: Codable, Sendable, Equatable {
    var `page`: Int
    var `size`: Int
}

struct CollectionsPage: Codable, Sendable, Equatable {
    var `items`: [BookCollection]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct BookCollection: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `userId`: Int
    var `mediaType`: String
    var `name`: String
    var `isPublic`: Bool
    var `isOwner`: Bool
    var `bookCount`: Int
}

struct CollectionPageQuery: Codable, Sendable, Equatable {
    var `page`: Int?
    var `size`: Int?
    var `q`: String?
    var `mediaType`: String?
    var `owned`: Bool?
}

struct CreateCollectionPayload: Codable, Sendable, Equatable {
    var `name`: String
    var `icon`: String
    var `description`: String?
    var `mediaType`: String?
    var `isPublic`: Bool?
    var `syncToKobo`: Bool?
}

struct BookIdsSelection: Codable, Sendable, Equatable {
    var `bookIds`: [Int]
}

struct BookMetadataUpdatePayload: Encodable, Sendable, Equatable {
    var `title`: FieldUpdate<String>?
    var `subtitle`: FieldUpdate<String>?
    var `description`: FieldUpdate<String>?
    var `publisher`: FieldUpdate<String>?
    var `publishedYear`: FieldUpdate<Int>?
    var `language`: FieldUpdate<String>?
    var `pageCount`: FieldUpdate<Int>?
    var `isbn13`: FieldUpdate<String>?
    var `isbn10`: FieldUpdate<String>?
    var `genres`: [String]?
    var `tags`: [String]?
    var `publishedDate`: FieldUpdate<String>?
    var `authors`: [String]?
}

struct BookMetadataAndLocksUpdatePayload: Encodable, Sendable, Equatable {
    var `metadata`: BookMetadataUpdatePayload?
    var `lockedFields`: [String]
}

struct FileReadingProgress: Codable, Sendable, Equatable {
    var `cfi`: String?
    var `pageNumber`: Double?
    var `percentage`: Double
    var `positionSeconds`: Double?
    var `mediaOverlayFragment`: String?
    var `mediaOverlaySectionIndex`: Double?
    var `koboLocationSource`: String?
    var `koboLocationType`: String?
    var `koboLocationValue`: String?
    var `koboContentSourceProgressPercent`: Double?
    var `koreaderProgress`: String?
    var `narrationPercentage`: Double?
    var `narrationUpdatedAt`: String?
    var `textUpdatedAt`: String?
}

struct SaveFileProgressPayload: Encodable, Sendable, Equatable {
    var `cfi`: String?
    var `pageNumber`: Double?
    var `positionSeconds`: Double?
    var `mediaOverlayFragment`: String?
    var `mediaOverlaySectionIndex`: Double?
    var `koboLocationSource`: String?
    var `koboLocationType`: String?
    var `koboLocationValue`: String?
    var `koboContentSourceProgressPercent`: Double?
    var `koreaderProgress`: String?
    var `percentage`: Double
    var `source`: String?
}

struct EpubBookInfo: Codable, Sendable, Equatable {
    var `containerPath`: String
    var `rootPath`: String
    var `spine`: [EpubSpineItem]
    var `manifest`: [EpubManifestItem]
    var `optionalFiles`: [String]?
}

struct EpubSpineItem: Codable, Sendable, Equatable {
    var `idref`: String
    var `href`: String
    var `mediaType`: String
    var `linear`: Bool
}

struct EpubManifestItem: Codable, Sendable, Equatable, Identifiable {
    var `id`: String
    var `href`: String
    var `mediaType`: String
    var `properties`: [String]?
    var `mediaOverlay`: String?
    var `size`: Int
}

enum CoverMedium: String, Codable, Sendable, CaseIterable, Identifiable {
    case ebook
    case audio
    var id: String { rawValue }
}

enum Permission: String, Sendable {
    case `libraryDownload` = "library_download"
    case `libraryUpload` = "library_upload"
    case `libraryEditMetadata` = "library_edit_metadata"
    case `libraryDeleteBooks` = "library_delete_books"
    case `bookDockAccess` = "book_dock_access"
    case `bookRequestAccess` = "book_request_access"
    case `podcastManageFeeds` = "podcast_manage_feeds"
    case `podcastDownload` = "podcast_download"
    case `podcastEditMetadata` = "podcast_edit_metadata"
    case `podcastManageRetention` = "podcast_manage_retention"
    case `podcastPurge` = "podcast_purge"
    case `demoRestricted` = "demo_restricted"
    case `koboSync` = "kobo_sync"
    case `koreaderSync` = "koreader_sync"
    case `hardcoverSync` = "hardcover_sync"
    case `readwiseSync` = "readwise_sync"
    case `storygraphSync` = "storygraph_sync"
    case `opdsAccess` = "opds_access"
    case `emailSend` = "email_send"
    case `manageEmail` = "manage_email"
    case `manageLibraries` = "manage_libraries"
    case `manageMetadataConfig` = "manage_metadata_config"
    case `manageIcons` = "manage_icons"
    case `manageAppSettings` = "manage_app_settings"
    case `manageBookDock` = "manage_book_dock"
    case `manageBookRequests` = "manage_book_requests"
    case `bookRequestAutoApprove` = "book_request_auto_approve"
    case `bookRequestSelfFulfill` = "book_request_self_fulfill"
    case `manageUsers` = "manage_users"
    case `viewUserActivity` = "view_user_activity"
    case `viewAuditLog` = "view_audit_log"
    case `notificationAccess` = "notification_access"
}
