// Generated by scripts/ipad/generate-contracts.mjs from @bookorbit/types.
// Regenerate after shared contract changes.
import Foundation

struct NativeAuthResponse: Codable, Sendable, Equatable {
    var `user`: AuthUser
    var `accessToken`: String
    var `accessTokenExpiresAt`: String
    var `refreshToken`: String
    var `refreshTokenExpiresAt`: String
    var `sessionId`: Int
}

struct AuthUser: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `username`: String
    var `name`: String
    var `active`: Bool
    var `isSuperuser`: Bool
    var `isDefaultPassword`: Bool
    var `permissions`: [String]
}

struct NativeCredentials: Codable, Sendable, Equatable {
    var `accessToken`: String
    var `accessTokenExpiresAt`: String
    var `refreshToken`: String
    var `refreshTokenExpiresAt`: String
    var `sessionId`: Int
}

struct LoginRequest: Codable, Sendable, Equatable {
    var `username`: String
    var `password`: String
    var `clientKind`: String?
    var `deviceLabel`: String?
}

struct RefreshRequest: Codable, Sendable, Equatable {
    var `refreshToken`: String?
}

struct ChangePasswordRequest: Codable, Sendable, Equatable {
    var `currentPassword`: String
    var `newPassword`: String
}

struct OidcStateResponse: Codable, Sendable, Equatable {
    var `state`: String
    var `authorizationEndpoint`: String
}

struct OidcCallbackRequest: Codable, Sendable, Equatable {
    var `code`: String
    var `codeVerifier`: String
    var `redirectUri`: String
    var `nonce`: String
    var `state`: String
    var `clientKind`: String?
    var `deviceLabel`: String?
}

struct LoginOptionsResponse: Codable, Sendable, Equatable {
    var `passwordLoginEnabled`: Bool
    var `allowRegistration`: Bool
    var `oidcProviders`: [OidcProviderPublic]
}

struct OidcProviderPublic: Codable, Sendable, Equatable {
    var `slug`: String
    var `displayName`: String
    var `enabled`: Bool
    var `iconUrl`: String?
    var `clientId`: String
    var `scopes`: String
}

struct Library: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `type`: String
    var `accessLevel`: String?
    var `name`: String
    var `bookCount`: Int?
}

struct BooksPage: Codable, Sendable, Equatable {
    var `items`: [BookCard]
    var `total`: Int
    var `page`: Int
    var `size`: Int
}

struct BookCard: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `title`: String?
    var `authors`: [String]
    var `files`: [BookFileRef]
    var `hasCover`: Bool
    var `coverVersion`: String
    var `readingProgress`: Double?
    var `seriesName`: String?
}

struct BookFileRef: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `format`: String?
    var `role`: String
    var `sizeBytes`: Double?
    var `mediaOverlay`: BookFileRefMediaOverlay?
}

struct BookFileRefMediaOverlay: Codable, Sendable, Equatable {
    var `available`: Bool
    var `durationSeconds`: Double?
}

struct BookDetail: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `libraryId`: Int
    var `libraryName`: String
    var `title`: String?
    var `description`: String?
    var `authors`: [BookDetailAuthorsItem]
    var `files`: [BookDetailFile]
    var `lockedFields`: [String]
    var `coverVersion`: String
}

struct BookDetailAuthorsItem: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `name`: String
    var `sortName`: String?
}

struct BookDetailFile: Codable, Sendable, Equatable, Identifiable {
    var `id`: Int
    var `format`: String?
    var `role`: String
    var `filename`: String?
    var `sizeBytes`: Double?
    var `durationSeconds`: Double?
}

struct BookQuery: Codable, Sendable, Equatable {
    var `sort`: [SortSpec]
    var `pagination`: BookQueryPagination
    var `q`: String?
    var `collapseSeries`: Bool?
}

struct SortSpec: Codable, Sendable, Equatable {
    var `field`: String
    var `dir`: String
}

struct BookQueryPagination: Codable, Sendable, Equatable {
    var `page`: Int
    var `size`: Int
}

enum Permission: String, Sendable {
    case `libraryDownload` = "library_download"
    case `libraryUpload` = "library_upload"
    case `libraryEditMetadata` = "library_edit_metadata"
    case `libraryDeleteBooks` = "library_delete_books"
    case `bookDockAccess` = "book_dock_access"
    case `bookRequestAccess` = "book_request_access"
    case `podcastManageFeeds` = "podcast_manage_feeds"
    case `podcastDownload` = "podcast_download"
    case `podcastEditMetadata` = "podcast_edit_metadata"
    case `podcastManageRetention` = "podcast_manage_retention"
    case `podcastPurge` = "podcast_purge"
    case `demoRestricted` = "demo_restricted"
    case `koboSync` = "kobo_sync"
    case `koreaderSync` = "koreader_sync"
    case `hardcoverSync` = "hardcover_sync"
    case `readwiseSync` = "readwise_sync"
    case `storygraphSync` = "storygraph_sync"
    case `opdsAccess` = "opds_access"
    case `emailSend` = "email_send"
    case `manageEmail` = "manage_email"
    case `manageLibraries` = "manage_libraries"
    case `manageMetadataConfig` = "manage_metadata_config"
    case `manageIcons` = "manage_icons"
    case `manageAppSettings` = "manage_app_settings"
    case `manageBookDock` = "manage_book_dock"
    case `manageBookRequests` = "manage_book_requests"
    case `bookRequestAutoApprove` = "book_request_auto_approve"
    case `bookRequestSelfFulfill` = "book_request_self_fulfill"
    case `manageUsers` = "manage_users"
    case `viewUserActivity` = "view_user_activity"
    case `viewAuditLog` = "view_audit_log"
    case `notificationAccess` = "notification_access"
}
